<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class TransferService {
    public const MAX_FILE_BYTES=1073741824;
    public static function normalize(array $input): array {
        Utils::requireFields($input,['native_transfer_id','native_transfer_version','sender_user_id','recipient_type','expected_size','media_class','declared_name','relationship','consent_status','copyright_basis','confidentiality_class','abuse_policy_version'],'transfer_envelope_incomplete');$sender=(int)$input['sender_user_id'];$type=Utils::key((string)$input['recipient_type'],16);$recipient=(int)($input['recipient_user_id']??0);$group=Utils::text((string)($input['recipient_group_id']??''),96);$size=(int)$input['expected_size'];if($sender<1||$size<1||$size>self::MAX_FILE_BYTES)throw new Error('transfer_bounds_invalid','Transfer identity or 1 GiB bound invalid.',413);if($type==='user'){if($recipient<1||$recipient===$sender)throw new Error('transfer_recipient_invalid','Recipient user is invalid.',400);}elseif($type==='group'){if($group==='')throw new Error('transfer_recipient_invalid','Recipient group is invalid.',400);}else throw new Error('transfer_recipient_type_invalid','Recipient type invalid.',400);if(!in_array((string)$input['consent_status'],['granted','not_required'],true))throw new Error('transfer_consent_denied','Transfer consent is not valid.',403);$nativeId=Utils::text((string)$input['native_transfer_id'],191);$relationship=Utils::key((string)$input['relationship'],48);$copyright=Utils::key((string)$input['copyright_basis'],48);$confidentiality=Utils::key((string)$input['confidentiality_class'],32);$abuseVersion=Utils::text((string)$input['abuse_policy_version'],32);if($nativeId===''||$relationship===''||$copyright===''||$confidentiality===''||$abuseVersion==='')throw new Error('transfer_envelope_incomplete','Transfer governance identity is incomplete.',400);$now=Utils::now();$requested=(int)($input['expires_at']??$now+604800);$expires=max($now+300,min($now+604800,$requested));return ['native_transfer_id'=>$nativeId,'native_transfer_version'=>max(1,(int)$input['native_transfer_version']),'sender_user_id'=>$sender,'recipient_type'=>$type,'recipient_user_id'=>$recipient,'recipient_group_id'=>$group,'recipient_ref_hash'=>Utils::hashReference($type.':'.($type==='user'?$recipient:$group)),'expected_size'=>$size,'media_class'=>Utils::key((string)$input['media_class'],32),'declared_name'=>Utils::filename((string)$input['declared_name']),'relationship'=>$relationship,'consent_status'=>(string)$input['consent_status'],'copyright_basis'=>$copyright,'clinical_confidentiality'=>Utils::bool($input['clinical_confidentiality']??false),'confidentiality_class'=>$confidentiality,'abuse_policy_version'=>$abuseVersion,'expires_at'=>$expires];
    }
    public static function create(array $input,array $uploadPolicy,array $quotaLimits=[]): array {
        RuntimeGuard::requireReady(['streaming']);$envelope=self::normalize($input);Auth::assertActor((int)$envelope['sender_user_id']);Auth::transferParties($envelope,'transfer_create');$policy=Policy::normalize($uploadPolicy,true);if($policy['owner_domain']!=='file17'||$policy['purpose']!=='verified-user-transfer'||!in_array($policy['privacy_class'],['C3','C4','C5'],true)||$policy['max_size_bytes']>self::MAX_FILE_BYTES)throw new Error('transfer_policy_invalid','Transfer policy must remain private, File 17-owned and within 1 GiB.',503);$decision=DomainRegistry::decision('file17','authorize_transfer_create',['transfer'=>$envelope,'policy'=>$policy]);if((int)$decision['object_version']!==(int)$envelope['native_transfer_version'])throw new Error('transfer_version_stale','Native transfer version is stale.',409);foreach(['relationship_allowed','consent_valid','copyright_valid','confidentiality_allowed','abuse_policy_allowed','recipient_authorized'] as $flag)if(($decision[$flag]??false)!==true)throw new Error('transfer_policy_denied','File 17 denied transfer policy.',403,['flag'=>$flag]);$id=Utils::id('tr');$record=['actor_id'=>$envelope['sender_user_id'],'transfer_id'=>$id]+$envelope+['policy'=>$policy,'policy_hash'=>$policy['policy_hash'],'status'=>'pending_upload','native_decision_version'=>$decision['contract_version'],'created_at'=>Utils::now()];$record=RecordStore::put('transfer',$id,$record);Audit::record('transfer_created',['transfer_id'=>$id,'actor_id'=>$envelope['sender_user_id'],'recipient_type'=>$envelope['recipient_type'],'expected_size'=>$envelope['expected_size']]);self::notify('transfer.created',$record);return $record;
    }
    public static function bindAsset(string $transferId,string $assetId,int $sender): array {Auth::assertActor($sender);$transfer=RecordStore::get('transfer',$transferId);if(!$transfer)throw new Error('transfer_not_found','Transfer not found.',404);if((int)$transfer['sender_user_id']!==$sender||($transfer['status']??'')!=='pending_upload'||(int)$transfer['expires_at']<=Utils::now())throw new Error('transfer_state_denied','Transfer cannot bind asset.',403);$asset=RecordStore::get('asset',$assetId);if(!$asset||($asset['owner_domain']??'')!=='file17'||($asset['owner_object']??'')!==$transfer['native_transfer_id']||(int)$asset['size']!==(int)$transfer['expected_size']||($asset['policy_hash']??'')!==$transfer['policy_hash'])throw new Error('transfer_asset_mismatch','Asset does not match transfer.',409);$transfer['asset_id']=$assetId;$transfer['status']='processing';$transfer['bound_at']=Utils::now();return RecordStore::put('transfer',$transferId,$transfer,(int)$transfer['version']);}
    public static function markReady(string $transferId): array {$t=RecordStore::get('transfer',$transferId);if(!$t)throw new Error('transfer_not_found','Transfer not found.',404);$asset=RecordStore::get('asset',(string)($t['asset_id']??''));if(!$asset||($asset['status']??'')!=='ready')throw new Error('transfer_asset_not_ready','Transfer asset is not ready.',409);Auth::transferParties($t,'transfer_ready');$decision=DomainRegistry::decision('file17','authorize_transfer_ready',['transfer'=>$t,'asset'=>$asset]);foreach(['relationship_allowed','consent_valid','copyright_valid','confidentiality_allowed','abuse_policy_allowed','recipient_authorized'] as $flag)if(($decision[$flag]??false)!==true)throw new Error('transfer_policy_denied','Transfer revalidation failed.',403,['flag'=>$flag]);$t['status']='ready';$t['ready_at']=Utils::now();$t=RecordStore::put('transfer',(string)$t['id'],$t,(int)$t['version']);self::notify('transfer.ready',$t);return $t;}
    public static function issueRecipientGrant(string $transferId,int $recipient,string $sessionId,array $context=[]): string {Auth::assertActor($recipient);$transfer=RecordStore::get('transfer',$transferId);if(!$transfer||($transfer['status']??'')!=='ready'||(int)$transfer['expires_at']<=Utils::now())throw new Error('transfer_not_ready','Transfer is not ready or expired.',409);if($transfer['recipient_type']==='user'&&(int)$transfer['recipient_user_id']!==$recipient)throw new Error('transfer_recipient_denied','Recipient does not match the transfer.',403);Auth::transferParties($transfer,'transfer_download');$decision=DomainRegistry::decision('file17','authorize_transfer_delivery',['transfer'=>$transfer,'recipient_user_id'=>$recipient,'session_id'=>$sessionId,'context'=>Utils::redact($context)]);if(($decision['recipient_authorized']??false)!==true)throw new Error('transfer_recipient_denied','Recipient is not authorized.',403);$audience=$transfer['recipient_type']==='user'?['type'=>'user','user_id'=>$recipient]:['type'=>'group','group_id'=>$transfer['recipient_group_id'],'user_id'=>$recipient];$deliveryContext=array_replace($context,['audience_type'=>'recipient','territory'=>$context['territory']??'GLOBAL']);return DeliveryService::issue((string)$transfer['asset_id'],null,$recipient,'file17-transfer',$audience,$deliveryContext,'download',['allow_ranges'=>$transfer['policy']['delivery']['allow_ranges'],'max_range_bytes'=>$transfer['policy']['delivery']['max_range_bytes']],$sessionId,300,50);}
    public static function revoke(string $transferId,int $actor,string $reason): array {Auth::assertActor($actor,'manage_options');$reason=Utils::key($reason,64);if($reason==='')throw new Error('transfer_revoke_reason_required','Transfer revoke reason required.',400);$transfer=RecordStore::get('transfer',$transferId);if(!$transfer)throw new Error('transfer_not_found','Transfer not found.',404);if(($transfer['status']??'')==='revoked')return $transfer;if($actor!==(int)$transfer['sender_user_id'])Auth::capability('media_reprocess');DomainRegistry::decision('file17','authorize_transfer_revoke',['transfer'=>$transfer,'actor_id'=>$actor,'reason'=>$reason]);$transfer['status']='revoked';$transfer['revoked_at']=Utils::now();$transfer['revoke_reason']=$reason;$transfer=RecordStore::put('transfer',$transferId,$transfer,(int)$transfer['version']);if(!empty($transfer['asset_id']))DeliveryService::revokeForAsset((string)$transfer['asset_id'],'transfer_revoked');self::notify('transfer.revoked',$transfer);return $transfer;}
    private static function notify(string $event,array $payload): void {if(function_exists('do_action'))do_action('scm_file19_notification',['event'=>$event,'payload'=>Utils::redact($payload)]);}
}

final class DownloadManagerService {
    public static function create(int $actor,string $assetId,?string $derivativeId,string $mode,array $context=[]): array {RuntimeGuard::requireReady(['streaming']);Auth::assertActor($actor);Auth::verifiedUser($actor,'download_create','file20',['asset_id'=>$assetId]);$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);if(!in_array($mode,['view','download'],true))throw new Error('download_mode_invalid','Download mode invalid.',400);if($mode==='download'&&!$asset['policy']['delivery']['allow_download'])throw new Error('download_denied','Download not allowed.',403);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_download',['asset'=>$asset,'derivative_id'=>$derivativeId,'actor_id'=>$actor,'mode'=>$mode,'context'=>Utils::redact($context)]);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner version stale.',409);$id=Utils::id('dl');$record=['actor_id'=>$actor,'download_id'=>$id,'asset_id'=>$assetId,'derivative_id'=>$derivativeId,'mode'=>$mode,'status'=>'authorized','owner_domain'=>$asset['owner_domain'],'object_version'=>$asset['object_version'],'created_at'=>Utils::now(),'expires_at'=>Utils::now()+3600];return RecordStore::put('download',$id,$record);}
    public static function grant(string $downloadId,int $actor,string $sessionId,array $context=[]): string {Auth::assertActor($actor);$download=RecordStore::get('download',$downloadId);if(!$download||($download['status']??'')!=='authorized'||(int)$download['expires_at']<=Utils::now())throw new Error('download_task_invalid','Download task invalid or expired.',403);if((int)$download['actor_id']!==$actor)throw new Error('download_actor_denied','Download task belongs to another user.',403);$audience=['type'=>'user','user_id'=>$actor];return DeliveryService::issue((string)$download['asset_id'],$download['derivative_id']?:null,$actor,'file20-download-manager',$audience,array_replace($context,['audience_type'=>'private']),(string)$download['mode'],['allow_ranges'=>true,'max_range_bytes'=>8388608],$sessionId,300,20);}
    public static function list(int $actor): array {Auth::assertActor($actor);return RecordStore::list('download',$actor);}
}

final class WorkspaceUploadService {
    public static function normalize(string $type,array $input,int $actor): array {if(!in_array($type,['image','audio'],true))throw new Error('workspace_type_invalid','Workspace upload type invalid.',400);Auth::assertActor($actor);Auth::verifiedUser($actor,'workspace_upload','workspace',['type'=>$type]);$base=['actor_id'=>$actor,'workspace_type'=>$type,'source'=>Utils::key((string)($input['source']??'device'),32),'strip_location_metadata'=>true,'created_at'=>Utils::now()];if($type==='image'){$rotation=(int)($input['rotation_degrees']??0);if(!in_array($rotation,[0,90,180,270],true))throw new Error('image_rotation_invalid','Image rotation invalid.',400);$quality=(int)($input['compression_quality']??82);if($quality<40||$quality>95)throw new Error('image_compression_quality_invalid','Image quality outside safe range.',400);$base+=['rotation_degrees'=>$rotation,'compression_quality'=>$quality,'crop'=>['requested'=>Utils::bool($input['crop_requested']??false),'x'=>max(0,(int)($input['crop_x']??0)),'y'=>max(0,(int)($input['crop_y']??0)),'width'=>max(0,(int)($input['crop_width']??0)),'height'=>max(0,(int)($input['crop_height']??0))]];}else{$trimStart=max(0,(float)($input['trim_start']??0));$trimEnd=max(0,(float)($input['trim_end']??0));if($trimEnd>0&&$trimEnd<=$trimStart)throw new Error('audio_trim_invalid','Audio trim range invalid.',400);$base+=['trim_start'=>$trimStart,'trim_end'=>$trimEnd,'normalize_loudness'=>Utils::bool($input['normalize_loudness']??true)];}return $base;}
}
