<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;
final class UploadService {
    public static function create(int $actor,array $meta,array $policy,string $idempotencyKey): array {
        Utils::requireRuntime(); $policy=Policy::validate($policy,true); $meta=Validator::uploadMetadata($meta,$policy); $fp=hash('sha256',Utils::json([$actor,$meta,Policy::fingerprint($policy)])); Idempotency::claim('upload-create',$idempotencyKey,$fp); RateLimiter::consume('upload:'.$actor,30,60);
        $decision=Auth::domainDecision($policy['domain'],'authorize_upload',['actor_id'=>$actor,'metadata'=>$meta,'policy'=>$policy]); $id=Utils::id('upl'); $session=['id'=>$id,'actor_id'=>$actor,'actor'=>$actor,'meta'=>$meta,'policy'=>$policy,'policy_hash'=>Policy::fingerprint($policy),'owner_object_version'=>(int)$decision['object_version'],'parts'=>[],'received'=>0,'status'=>'uploading','expires_at'=>Utils::now()+3600]; $session=RecordStore::put('upload',$id,$session); Audit::record('upload_created',['upload_id'=>$id,'actor'=>$actor,'domain'=>$policy['domain']]); return self::public($session);
    }
    public static function putPart(string $id,int $actor,int $number,string $bytes,string $sha256): array { $s=self::session($id); self::assertActor($s,$actor); if($s['status']!=='uploading'||$s['expires_at']<Utils::now()) throw new Error('upload_not_active','Upload is not active.',409); if($number<1||$number>$s['policy']['max_upload_parts']) throw new Error('upload_part_invalid','Invalid upload part number.',400); if(!hash_equals(strtolower($sha256),hash('sha256',$bytes))) throw new Error('upload_part_checksum_invalid','Part checksum mismatch.',422); $old=$s['parts'][$number]??null; if($old && !hash_equals($old['sha256'],$sha256)) throw new Error('upload_part_overlap','Part number already contains different bytes.',409); if(!$old){$s['parts'][$number]=PartStore::put($id,$number,$bytes,$sha256);$s['received']+=strlen($bytes);} if($s['received']>$s['meta']['size']) throw new Error('upload_size_overflow','Received bytes exceed declared size.',413); $s=RecordStore::put('upload',$id,$s,(int)$s['version']); return ['upload_id'=>$id,'part'=>$number,'received'=>$s['received']]; }
    public static function complete(string $id,int $actor,string $idempotencyKey): array { $s=self::session($id); self::assertActor($s,$actor); Idempotency::claim('upload-complete',$idempotencyKey,$s['policy_hash']); if(in_array($s['status'],['quarantined','ready'],true)) return self::public($s); ksort($s['parts']); $bytes=''; foreach($s['parts'] as $p)$bytes.=PartStore::get($p); if(strlen($bytes)!==$s['meta']['size']) throw new Error('upload_incomplete','Uploaded byte count is incomplete.',409); if($s['meta']['sha256']!==''&&!hash_equals($s['meta']['sha256'],hash('sha256',$bytes))) throw new Error('upload_checksum_invalid','Completed upload checksum mismatch.',422); if(!Validator::magicMatches(self::temp($bytes),$s['meta']['mime'])) throw new Error('upload_magic_mismatch','File signature does not match MIME type.',415); Auth::domainDecision($s['policy']['domain'],'authorize_upload',['actor_id'=>$actor,'metadata'=>$s['meta'],'policy'=>$s['policy'],'completion'=>true,'object_version'=>$s['owner_object_version']]); $objectKey=hash('sha256',$s['policy']['domain'].'|'.$s['policy']['purpose'].'|'.hash('sha256',$bytes)); $stored=ProviderRegistry::store()->put($objectKey,$bytes,['upload_id'=>$id,'privacy_class'=>$s['policy']['privacy_class']]); foreach($s['parts'] as $part) PartStore::delete($part); $s['status']='quarantined'; $s['object']=$stored; $s['scan_status']='pending'; $s['parts']=[]; $s=RecordStore::put('upload',$id,$s,(int)$s['version']); RecordStore::put('asset',$id,['actor_id'=>$actor,'status'=>'quarantined','asset_id'=>$id,'owner_domain'=>$s['policy']['domain'],'owner_object'=>(string)($s['policy']['owner_object']??$id),'object_version'=>$s['owner_object_version'],'object_key'=>$objectKey,'privacy_class'=>$s['policy']['privacy_class'],'mime'=>$s['meta']['mime'],'required_scans'=>$s['policy']['required_scans'],'scan_status'=>'pending']); Audit::record('upload_quarantined',['upload_id'=>$id,'object_key'=>$objectKey]); return self::public($s); }
    private static function temp(string $bytes): string { $p=tempnam(sys_get_temp_dir(),'scm'); file_put_contents($p,$bytes); register_shutdown_function(static fn()=>@unlink($p)); return $p; }
    private static function session(string $id): array { $s=RecordStore::get('upload',$id); if(!$s) throw new Error('upload_not_found','Upload not found.',404); return $s; }
    private static function assertActor(array $s,int $actor): void { if($actor<1||$s['actor']!==$actor) throw new Error('upload_actor_denied','Upload actor mismatch.',403); }
    private static function public(array $s): array { unset($s['parts']); return Utils::redact($s); }
}
