<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class JobService {
    public const PRIORITIES=['security'=>100,'revocation'=>95,'deletion'=>90,'interactive'=>70,'normal'=>50,'bulk'=>20,'maintenance'=>10];
    public static function graph(string $assetId,array $policy): array {
        $nodes=[
            ['name'=>'probe','depends'=>[],'priority'=>'security'],['name'=>'scan','depends'=>['probe'],'priority'=>'security'],
            ['name'=>'metadata','depends'=>['scan'],'priority'=>'normal'],['name'=>'transform','depends'=>['metadata'],'priority'=>'normal'],
            ['name'=>'validate_outputs','depends'=>['transform'],'priority'=>'security'],['name'=>'store_derivatives','depends'=>['validate_outputs'],'priority'=>'normal'],
            ['name'=>'manifest_switch','depends'=>['store_derivatives'],'priority'=>'interactive'],
        ];
        $ids=[];foreach($nodes as $node){$id=hash('sha256',$assetId.'|'.$node['name'].'|'.$policy['policy_hash']);$ids[$node['name']]=$id;RecordStore::put('job',$id,['actor_id'=>0,'job_id'=>$id,'asset_id'=>$assetId,'job_type'=>$node['name'],'depends_on'=>$node['depends'],'priority'=>$node['priority'],'priority_weight'=>self::PRIORITIES[$node['priority']],'tenant'=>$policy['owner_domain'],'status'=>'queued','attempts'=>0,'max_attempts'=>5,'next_attempt_at'=>Utils::now(),'created_at'=>Utils::now()]);}return $ids;
    }
    public static function lease(string $workerId,array $capabilities,int $leaseSeconds=120): ?array {
        $now=Utils::now();$queued=RecordStore::list('job');$eligible=[];foreach($queued as $job){if(!in_array(($job['status']??''),['queued','retry'],true)||(int)($job['next_attempt_at']??0)>$now)continue;if(!in_array((string)$job['job_type'],$capabilities,true))continue;if(!self::dependenciesComplete($job))continue;$age=max(0,$now-(int)($job['created_at']??$now));$fairness=min(30,(int)floor($age/60));$tenantPenalty=self::tenantActiveLeases((string)$job['tenant'])*10;$job['_score']=(int)$job['priority_weight']+$fairness-$tenantPenalty;$eligible[]=$job;}if($eligible===[])return null;usort($eligible,fn($a,$b)=>$b['_score']<=>$a['_score'] ?: ((int)$a['created_at']<=>(int)$b['created_at']));$job=$eligible[0];unset($job['_score']);$fresh=RecordStore::get('job',(string)$job['id']);if(!$fresh||!in_array(($fresh['status']??''),['queued','retry'],true))return null;$fresh['status']='leased';$fresh['lease_owner']=Utils::text($workerId,96);$fresh['lease_token']=Utils::id('lease');$fresh['lease_expires_at']=$now+max(30,min(600,$leaseSeconds));$fresh['heartbeat_at']=$now;$fresh['attempts']=(int)$fresh['attempts']+1;return RecordStore::put('job',(string)$fresh['id'],$fresh,(int)$fresh['version']);
    }
    private static function tenantActiveLeases(string $tenant): int {return count(array_filter(RecordStore::list('job'),fn($j)=>($j['tenant']??'')===$tenant&&($j['status']??'')==='leased'&&(int)($j['lease_expires_at']??0)>Utils::now()));}
    private static function dependenciesComplete(array $job): bool {foreach((array)($job['depends_on']??[]) as $name){$id=hash('sha256',$job['asset_id'].'|'.$name.'|'.(RecordStore::get('asset',(string)$job['asset_id'])['policy_hash']??''));$dep=RecordStore::get('job',$id);if(!$dep||($dep['status']??'')!=='completed')return false;}return true;}
    public static function leaseSpecific(string $jobId,string $workerId,int $leaseSeconds=120): array {
        $job=RecordStore::get('job',$jobId);if(!$job||!in_array(($job['status']??''),['queued','retry'],true)||(int)($job['next_attempt_at']??0)>Utils::now()||!self::dependenciesComplete($job))throw new Error('job_not_leaseable','Requested job is not leaseable.',409,['job_id'=>$jobId]);
        $job['status']='leased';$job['lease_owner']=Utils::text($workerId,96);$job['lease_token']=Utils::id('lease');$job['lease_expires_at']=Utils::now()+max(30,min(600,$leaseSeconds));$job['heartbeat_at']=Utils::now();$job['attempts']=(int)$job['attempts']+1;return RecordStore::put('job',$jobId,$job,(int)$job['version']);
    }
    public static function heartbeat(string $jobId,string $leaseToken,int $extend=120): array {$j=RecordStore::get('job',$jobId);if(!$j||($j['status']??'')!=='leased'||!hash_equals((string)$j['lease_token'],$leaseToken))throw new Error('job_lease_invalid','Job lease invalid.',409);if((int)$j['lease_expires_at']<=Utils::now())throw new Error('job_lease_expired','Job lease expired.',409);$j['heartbeat_at']=Utils::now();$j['lease_expires_at']=Utils::now()+max(30,min(600,$extend));return RecordStore::put('job',$jobId,$j,(int)$j['version']);}
    public static function complete(string $jobId,string $leaseToken,array $result=[]): array {$j=RecordStore::get('job',$jobId);if(!$j||($j['status']??'')!=='leased'||!hash_equals((string)$j['lease_token'],$leaseToken))throw new Error('job_lease_invalid','Job lease invalid.',409);$j['status']='completed';$j['result']=Utils::redact($result);$j['completed_at']=Utils::now();unset($j['lease_token']);return RecordStore::put('job',$jobId,$j,(int)$j['version']);}
    public static function fail(string $jobId,string $leaseToken,string $code,bool $retryable=true): array {$j=RecordStore::get('job',$jobId);if(!$j||($j['status']??'')!=='leased'||!hash_equals((string)$j['lease_token'],$leaseToken))throw new Error('job_lease_invalid','Job lease invalid.',409);$j['last_error']=Utils::key($code,64);$j['failed_at']=Utils::now();if($retryable&&(int)$j['attempts']<(int)$j['max_attempts']){$j['status']='retry';$j['next_attempt_at']=Utils::now()+min(3600,2**(int)$j['attempts']*15);}else{$j['status']='dead_letter';$j['dead_lettered_at']=Utils::now();}unset($j['lease_token']);return RecordStore::put('job',$jobId,$j,(int)$j['version']);}
    public static function recoverOrphans(): int {$count=0;foreach(RecordStore::list('job') as $j){if(($j['status']??'')==='leased'&&(int)($j['lease_expires_at']??0)<=Utils::now()){$j['status']=(int)$j['attempts']<(int)$j['max_attempts']?'retry':'dead_letter';$j['next_attempt_at']=Utils::now();$j['last_error']='lease_expired';unset($j['lease_token']);RecordStore::put('job',(string)$j['id'],$j,(int)$j['version']);$count++;}}return $count;}
    public static function retryDeadLetter(string $jobId,int $actor,string $reason): array {Auth::capability('media_reprocess');$j=RecordStore::get('job',$jobId);if(!$j||($j['status']??'')!=='dead_letter')throw new Error('dead_letter_not_found','Dead-letter job not found.',404);$j['status']='queued';$j['attempts']=0;$j['next_attempt_at']=Utils::now();$j['operator_reason']=Utils::text($reason,500);$j['operator_id']=$actor;return RecordStore::put('job',$jobId,$j,(int)$j['version']);}
}

final class DerivativeService {
    public static function store(string $assetId,string $kind,$stream,array $lineage,array $policy): array {
        if(!is_resource($stream))throw new Error('derivative_stream_invalid','Derivative output stream invalid.',500);$stats=Utils::streamHash($stream);$id=Utils::id('drv');$objectKey=hash('sha256','derivative|'.$assetId.'|'.$kind.'|'.$stats['sha256'].'|'.$policy['policy_hash']);$stored=ProviderRegistry::store()->putStream($objectKey,$stream,['scope'=>'derivative','asset_id'=>$assetId,'kind'=>$kind,'privacy_class'=>$policy['privacy_class']]);$stored['provider_id']=ProviderRegistry::activeId();$record=['actor_id'=>0,'derivative_id'=>$id,'asset_id'=>$assetId,'kind'=>Utils::key($kind,64),'status'=>'validated','sha256'=>$stats['sha256'],'size'=>$stats['size'],'object_key'=>$stored['object_key'],'storage'=>$stored,'lineage'=>self::lineage($lineage),'created_at'=>Utils::now(),'superseded_by'=>null];return RecordStore::put('derivative',$id,$record);}
    private static function lineage(array $l): array {Utils::requireFields($l,['source_sha256','job_id','tool','tool_version','preset','preset_version'],'lineage_incomplete');return ['source_sha256'=>(string)$l['source_sha256'],'job_id'=>Utils::text((string)$l['job_id'],96),'tool'=>Utils::text((string)$l['tool'],96),'tool_version'=>Utils::text((string)$l['tool_version'],64),'preset'=>Utils::text((string)$l['preset'],96),'preset_version'=>Utils::text((string)$l['preset_version'],64),'dimensions'=>$l['dimensions']??null,'bitrate'=>$l['bitrate']??null,'pages'=>$l['pages']??null,'duration'=>$l['duration']??null,'created_at'=>Utils::now()];}
    public static function manifest(string $assetId,array $derivativeIds,int $expectedVersion): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$items=[];foreach($derivativeIds as $id){$d=RecordStore::get('derivative',(string)$id);if(!$d||($d['asset_id']??'')!==$assetId||($d['status']??'')!=='validated')throw new Error('derivative_not_validated','Derivative is not validated.',409,['derivative_id'=>$id]);$items[]=['derivative_id'=>$d['id'],'kind'=>$d['kind'],'sha256'=>$d['sha256'],'size'=>$d['size'],'lineage'=>$d['lineage']];}$manifestId=Utils::id('man');$manifest=['actor_id'=>0,'manifest_id'=>$manifestId,'asset_id'=>$assetId,'manifest_version'=>$expectedVersion+1,'status'=>'active','derivatives'=>$items,'created_at'=>Utils::now()];$manifest=RecordStore::put('manifest',$manifestId,$manifest);$old=$asset['active_manifest_id']??null;$asset['active_manifest_id']=$manifestId;$asset['manifest_version']=$manifest['manifest_version'];$asset['processing_status']='completed';$asset['status']='ready';$asset['ready_at']=Utils::now();RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);if($old){$oldManifest=RecordStore::get('manifest',(string)$old);if($oldManifest){$oldManifest['status']='superseded';$oldManifest['superseded_by']=$manifestId;RecordStore::put('manifest',(string)$old,$oldManifest,(int)$oldManifest['version']);}}Audit::record('manifest_atomically_switched',['asset_id'=>$assetId,'manifest_id'=>$manifestId,'previous_manifest'=>$old]);return $manifest;}
    public static function forAsset(string $assetId): array {return array_values(array_filter(RecordStore::list('derivative'),fn($d)=>($d['asset_id']??'')===$assetId));}
}

final class ImagePipeline {
    public static function run(array $asset,$source,string $jobId): array {$policy=$asset['policy'];$meta=MetadataPolicy::transform('image',['stream'=>$source,'mime'=>$asset['mime'],'sha256'=>$asset['sha256']],$policy);$clean=$meta['output_stream'];$spec=['orientation'=>'auto','color_profile'=>'srgb','max_width'=>$policy['max_width'],'max_height'=>$policy['max_height'],'max_pixels'=>$policy['max_pixels'],'formats'=>['jpeg','webp','avif'],'fallback'=>'jpeg','derivatives'=>$policy['derivative_set'],'quality_presets'=>['thumb'=>78,'small'=>80,'medium'=>82,'large'=>84]];try{$result=ToolRunner::transform('image-pipeline',['stream'=>$clean,'mime'=>$asset['mime']],$spec);}finally{fclose($clean);}return self::validateOutputs($result,$asset,$jobId);}
    private static function validateOutputs(array $result,array $asset,string $jobId): array {$outs=(array)($result['outputs']??[]);if($outs===[])throw new Error('image_pipeline_empty','Image pipeline returned no outputs.',422);$ids=[];foreach($outs as $out){if(!is_array($out)||!is_resource($out['stream']??null)||($out['width']??0)<1||($out['height']??0)<1||!in_array(($out['format']??''),['jpeg','png','webp','avif'],true))throw new Error('image_output_invalid','Image output invalid.',422);$ids[]=DerivativeService::store($asset['asset_id'],(string)$out['kind'],$out['stream'],['source_sha256'=>$asset['sha256'],'job_id'=>$jobId,'tool'=>$result['worker']['id'],'tool_version'=>$result['worker']['version'],'preset'=>(string)$out['kind'],'preset_version'=>(string)($out['preset_version']??'1'),'dimensions'=>[(int)$out['width'],(int)$out['height']]],$asset['policy'])['id'];}return $ids;}
}

final class AvPipeline {
    public static function run(array $asset,$source,string $jobId): array {$spec=$asset['media_class']==='video'?['probe'=>true,'adaptive'=>true,'manifests'=>['hls','dash'],'video_codecs'=>['h264','vp9','av1'],'audio_codecs'=>['aac','opus'],'poster'=>true,'waveform'=>true,'loudness'=>'EBU-R128','captions_reference'=>true,'segment_hashes'=>true,'duration_limit'=>$asset['policy']['max_duration_seconds']]:['probe'=>true,'audio_codecs'=>['aac','opus','mp3'],'waveform'=>true,'loudness'=>'EBU-R128','captions_reference'=>true,'duration_limit'=>$asset['policy']['max_duration_seconds']];$result=ToolRunner::transform($asset['media_class'].'-pipeline',['stream'=>$source,'mime'=>$asset['mime']],$spec);$probe=(array)($result['probe']??[]);if(($probe['supported']??false)!==true||(int)($probe['duration_seconds']??0)<1)throw new Error('av_probe_failed','Audio/video probe failed.',422);if($asset['policy']['max_duration_seconds']>0&&(int)$probe['duration_seconds']>$asset['policy']['max_duration_seconds'])throw new Error('duration_limit_exceeded','Media duration exceeds policy.',413);$outs=(array)($result['outputs']??[]);if($outs===[])throw new Error('av_pipeline_empty','Audio/video pipeline returned no outputs.',422);$ids=[];foreach($outs as $out){if(!is_resource($out['stream']??null)||empty($out['kind'])||empty($out['sha256']))throw new Error('av_output_invalid','Audio/video output invalid.',422);$stats=Utils::streamHash($out['stream']);if(!hash_equals((string)$out['sha256'],$stats['sha256']))throw new Error('av_output_hash_mismatch','Audio/video output hash mismatch.',422);$ids[]=DerivativeService::store($asset['asset_id'],(string)$out['kind'],$out['stream'],['source_sha256'=>$asset['sha256'],'job_id'=>$jobId,'tool'=>$result['worker']['id'],'tool_version'=>$result['worker']['version'],'preset'=>(string)$out['kind'],'preset_version'=>(string)($out['preset_version']??'1'),'bitrate'=>$out['bitrate']??null,'duration'=>$probe['duration_seconds']],$asset['policy'])['id'];}if($asset['media_class']==='video'){foreach(['hls-manifest','poster'] as $required)if(!array_filter($outs,fn($o)=>($o['kind']??'')===$required))throw new Error('video_derivative_missing','Required video derivative missing.',422,['kind'=>$required]);}return $ids;}
}

final class DocumentPipeline {
    public static function run(array $asset,$source,string $jobId): array {$rights=$asset['rights'];$allowText=in_array('extract_text',(array)$rights['allowed_operations'],true);$allowOcr=in_array('ocr',(array)$rights['allowed_operations'],true);$spec=['structural_validation'=>true,'max_pages'=>$asset['policy']['max_pages'],'preview_raster'=>true,'extract_text'=>$allowText,'ocr'=>$allowOcr,'suppress_active_content'=>true,'font_render_sandbox'=>true,'preserve_rights_metadata'=>true];$result=ToolRunner::transform('document-pipeline',['stream'=>$source,'mime'=>$asset['mime']],$spec);if(($result['structure']['valid']??false)!==true||($result['active_content_suppressed']??false)!==true)throw new Error('document_processing_failed','Document processing failed safety validation.',422);$pages=(int)($result['structure']['pages']??0);if($pages<1||($asset['policy']['max_pages']>0&&$pages>$asset['policy']['max_pages']))throw new Error('document_page_limit','Document page count outside policy.',413);$outs=(array)($result['outputs']??[]);if($outs===[])throw new Error('document_pipeline_empty','Document pipeline returned no outputs.',422);$ids=[];foreach($outs as $out){if(!is_resource($out['stream']??null)||empty($out['kind']))throw new Error('document_output_invalid','Document output invalid.',422);if(($out['kind']??'')==='text'&&!$allowText)throw new Error('unauthorized_text_output','Unauthorized text extraction output.',500);if(($out['kind']??'')==='ocr'&&!$allowOcr)throw new Error('unauthorized_ocr_output','Unauthorized OCR output.',500);$ids[]=DerivativeService::store($asset['asset_id'],(string)$out['kind'],$out['stream'],['source_sha256'=>$asset['sha256'],'job_id'=>$jobId,'tool'=>$result['worker']['id'],'tool_version'=>$result['worker']['version'],'preset'=>(string)$out['kind'],'preset_version'=>(string)($out['preset_version']??'1'),'pages'=>$pages],$asset['policy'])['id'];}return $ids;}
}

final class ProcessingService {
    public static function start(string $assetId): array {RuntimeGuard::requireReady(['streaming']);$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);if(($asset['status']??'')!=='quarantined')throw new Error('asset_state_invalid','Only quarantined assets may enter processing.',409);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_processing',['asset'=>$asset,'operation'=>'start']);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner version changed.',409);$jobs=JobService::graph($assetId,$asset['policy']);$asset['processing_status']='queued';$asset['job_graph']=$jobs;RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);Audit::record('processing_graph_created',['asset_id'=>$assetId,'jobs'=>array_keys($jobs)]);return $jobs;}
    public static function execute(string $assetId,string $workerId='inline-worker'): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);if(empty($asset['job_graph']))self::start($assetId);$derivatives=[];foreach(['probe','scan','metadata','transform','validate_outputs','store_derivatives','manifest_switch'] as $type){$jobId=$asset['job_graph'][$type]??hash('sha256',$assetId.'|'.$type.'|'.$asset['policy_hash']);$job=RecordStore::get('job',$jobId);if(!$job)throw new Error('job_missing','Processing job missing.',500,['job'=>$type]);if(($job['status']??'')==='completed'){if($type==='transform')$derivatives=(array)($job['result']['derivatives']??$derivatives);continue;}$leased=JobService::leaseSpecific($jobId,$workerId);try{$result=self::executeNode($type,$assetId,$jobId,$derivatives);if($type==='transform')$derivatives=(array)$result['derivatives'];JobService::complete($jobId,(string)$leased['lease_token'],$result);}catch(\Throwable $e){JobService::fail($jobId,(string)$leased['lease_token'],$e instanceof Error?$e->errorCode:'unexpected',!($e instanceof Error)||$e->httpStatus>=500);$asset=RecordStore::get('asset',$assetId)??$asset;$asset['processing_status']='failed';$asset['last_processing_error']=$e instanceof Error?$e->errorCode:'unexpected';RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);throw $e;}$asset=RecordStore::get('asset',$assetId)??$asset;}return RecordStore::get('asset',$assetId)??throw new Error('asset_not_found','Asset vanished.',500);}
    private static function executeNode(string $type,string $assetId,string $jobId,array $derivatives): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$source=ProviderRegistry::store()->openStream((string)$asset['object_key']);try{return match($type){
            'probe'=>['probe'=>ToolRunner::probe(self::streamToTempPath($source),$asset['mime'],$asset['policy'])],
            'scan'=>self::scanNode($source,$asset),
            'metadata'=>['metadata_policy'=>'validated'],
            'transform'=>['derivatives'=>self::pipeline($asset,$source,$jobId)],
            'validate_outputs'=>self::validateDerivatives($assetId,$derivatives),
            'store_derivatives'=>['derivatives'=>$derivatives,'stored'=>true],
            'manifest_switch'=>['manifest'=>DerivativeService::manifest($assetId,$derivatives,(int)$asset['manifest_version'])],
            default=>throw new Error('job_type_unknown','Unknown processing job.',500),
        };}finally{fclose($source);}}
    private static function scanNode($source,array $asset): array {$scans=ScannerRegistry::scan($source,$asset['policy']['required_scans'],['asset_id'=>$asset['asset_id'],'mime'=>$asset['mime'],'policy'=>$asset['policy']]);$signal=SafetySignalService::evaluate($source,$asset);if(($signal['status']??'')==='pending_review'&&$asset['policy']['safety']['require_reviewer_for_low_confidence'])throw new Error('safety_review_required','Low-confidence technical safety signal requires review.',409,['signal_id'=>$signal['id']]);$asset['scan_status']='passed';$asset['scan_results']=$scans;$asset['safety_signal_id']=$signal['id'];RecordStore::put('asset',$asset['asset_id'],$asset,(int)$asset['version']);return ['scans'=>$scans,'safety_signal'=>$signal['id']];}
    private static function pipeline(array $asset,$source,string $jobId): array {rewind($source);return match($asset['media_class']){'image'=>ImagePipeline::run($asset,$source,$jobId),'audio','video'=>AvPipeline::run($asset,$source,$jobId),'document'=>DocumentPipeline::run($asset,$source,$jobId),default=>self::genericPipeline($asset,$source,$jobId)};}
    private static function genericPipeline(array $asset,$source,string $jobId): array {$result=ToolRunner::transform('generic-safe-copy',['stream'=>$source,'mime'=>$asset['mime']],['strip_metadata'=>true,'validate_output'=>true]);$out=$result['output_stream']??null;if(!is_resource($out))throw new Error('generic_output_invalid','Generic processing output invalid.',422);return [DerivativeService::store($asset['asset_id'],'safe-copy',$out,['source_sha256'=>$asset['sha256'],'job_id'=>$jobId,'tool'=>$result['worker']['id'],'tool_version'=>$result['worker']['version'],'preset'=>'safe-copy','preset_version'=>'1'],$asset['policy'])['id']];}
    private static function validateDerivatives(string $assetId,array $ids): array {if($ids===[])throw new Error('derivative_set_empty','No derivatives produced.',422);foreach($ids as $id){$d=RecordStore::get('derivative',(string)$id);if(!$d||($d['asset_id']??'')!==$assetId||($d['status']??'')!=='validated')throw new Error('derivative_validation_failed','Derivative validation failed.',422);$stream=ProviderRegistry::store()->openStream((string)$d['object_key']);try{$stats=Utils::streamHash($stream);if(!hash_equals((string)$d['sha256'],$stats['sha256'])||(int)$d['size']!==(int)$stats['size'])throw new Error('derivative_integrity_failed','Derivative integrity failed.',422);}finally{fclose($stream);}}return ['validated'=>count($ids)];}
    private static function streamToTempPath($stream): string {$path=tempnam(sys_get_temp_dir(),'scm-probe-');if($path===false)throw new Error('temp_unavailable','Probe workspace unavailable.',500);$out=fopen($path,'wb');if($out===false)throw new Error('temp_unavailable','Probe workspace unavailable.',500);rewind($stream);stream_copy_to_stream($stream,$out);fclose($out);rewind($stream);register_shutdown_function(static fn()=>@unlink($path));return $path;}
}
