<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class Validator {
    private const SIGNATURES=[
        'application/pdf'=>['25504446'],
        'image/jpeg'=>['ffd8ff'],'image/png'=>['89504e470d0a1a0a'],'image/gif'=>['47494638'],'image/webp'=>['52494646'],
        'audio/mpeg'=>['494433','fffb','fff3','fff2'],'audio/wav'=>['52494646'],'audio/ogg'=>['4f676753'],'video/mp4'=>['000000','66747970'],'video/webm'=>['1a45dfa3'],
        'application/zip'=>['504b0304','504b0506','504b0708'],
    ];
    public static function inspectStream($stream,string $filename,string $declaredMime,array $policy): array {
        if(!is_resource($stream))throw new Error('stream_invalid','Invalid source stream.',500);$stats=Utils::streamHash($stream);if($stats['size']<1||(int)$stats['size']>(int)$policy['max_size_bytes'])throw new Error('source_size_invalid','Source size outside policy.',413);
        $temp=tempnam(sys_get_temp_dir(),'scm-inspect-');if($temp===false)throw new Error('temp_unavailable','Inspection workspace unavailable.',500);$out=fopen($temp,'wb');if($out===false)throw new Error('temp_unavailable','Inspection workspace unavailable.',500);rewind($stream);stream_copy_to_stream($stream,$out);fclose($out);rewind($stream);
        try{$mime=self::detectMime($temp);$declared=strtolower($declaredMime);if($mime!==$declared)throw new Error('declared_mime_mismatch','Declared MIME does not match source signature.',415,['declared'=>$declared,'detected'=>$mime]);if(!in_array($mime,$policy['allowed_mime_types'],true))throw new Error('mime_denied','Detected MIME denied by policy.',415);self::magicMatches($temp,$mime,true);self::assertFilename($filename,$mime,(array)$policy['allowed_extensions']);$structure=self::structuralProbe($temp,$mime,$policy);$fingerprint=hash('sha256',$stats['sha256'].'|'.$mime.'|'.Utils::canonicalJson($structure));return ['sha256'=>$stats['sha256'],'size'=>$stats['size'],'mime'=>$mime,'structure'=>$structure,'fingerprint'=>$fingerprint];}finally{@unlink($temp);}
    }
    public static function detectMime(string $path): string {if(!is_file($path))throw new Error('source_missing','Source unavailable.',500);$finfo=function_exists('finfo_open')?finfo_open(FILEINFO_MIME_TYPE):false;$mime=$finfo?finfo_file($finfo,$path):false;if($finfo)finfo_close($finfo);$mime=is_string($mime)?strtolower($mime):'application/octet-stream';$head=file_get_contents($path,false,null,0,32);if(!is_string($head))throw new Error('source_read_failed','Cannot read source.',500);$hex=strtolower(bin2hex($head));if(str_starts_with($head,'%PDF-'))return 'application/pdf';if(str_starts_with($hex,'ffd8ff'))return 'image/jpeg';if(str_starts_with($hex,'89504e470d0a1a0a'))return 'image/png';if(str_starts_with($head,'GIF8'))return 'image/gif';if(str_starts_with($head,'RIFF')&&substr($head,8,4)==='WEBP')return 'image/webp';if(str_starts_with($head,'RIFF')&&substr($head,8,4)==='WAVE')return 'audio/wav';if(str_starts_with($head,'OggS'))return 'audio/ogg';if(str_starts_with($head,"\x1A\x45\xDF\xA3"))return 'video/webm';if(strlen($head)>=12&&substr($head,4,4)==='ftyp')return 'video/mp4';if(str_starts_with($head,'ID3')||(isset($head[0],$head[1])&&ord($head[0])===0xff&&(ord($head[1])&0xe0)===0xe0))return 'audio/mpeg';if(str_starts_with($head,'PK'))return 'application/zip';return $mime;}
    public static function magicMatches(string $path,string $mime,bool $throw=false): bool {$head=file_get_contents($path,false,null,0,32);$hex=is_string($head)?strtolower(bin2hex($head)):'';$match=false;if($mime==='video/mp4')$match=is_string($head)&&strlen($head)>=12&&substr($head,4,4)==='ftyp';elseif($mime==='image/webp')$match=is_string($head)&&str_starts_with($head,'RIFF')&&substr($head,8,4)==='WEBP';elseif($mime==='audio/wav')$match=is_string($head)&&str_starts_with($head,'RIFF')&&substr($head,8,4)==='WAVE';else foreach(self::SIGNATURES[$mime]??[] as $sig)if(str_starts_with($hex,$sig)){$match=true;break;}if(!$match&&$throw)throw new Error('magic_signature_mismatch','File signature does not match allowed type.',415,['mime'=>$mime]);return $match;}
    private static function assertFilename(string $filename,string $mime,array $allowed): void {$safe=Utils::filename($filename);$lower=strtolower($safe);if(preg_match('/\.(php\d*|phtml|phar|cgi|pl|py|js|html?|svg|exe|dll|com|bat|cmd|sh)(\.|$)/i',$lower))throw new Error('executable_filename_denied','Executable or active-content filename denied.',415);$parts=explode('.',$lower);if(count($parts)>2){$danger=array_slice($parts,0,-1);foreach($danger as $p)if(in_array($p,['php','phtml','phar','exe','js','html','svg'],true))throw new Error('double_extension_denied','Dangerous double extension denied.',415);}if($allowed!==[]){$ext=strtolower(pathinfo($safe,PATHINFO_EXTENSION));if(!in_array($ext,$allowed,true))throw new Error('extension_denied','Extension denied.',415);} }
    private static function structuralProbe(string $path,string $mime,array $policy): array {$size=filesize($path);$probe=['mime'=>$mime,'byte_size'=>(int)$size];if(str_starts_with($mime,'image/')){$info=@getimagesize($path);if(!is_array($info)||($info[0]??0)<1||($info[1]??0)<1)throw new Error('image_structure_invalid','Image structure invalid.',422);$pixels=(int)$info[0]*(int)$info[1];$limit=(int)($policy['max_pixels']??0);if($limit>0&&$pixels>$limit)throw new Error('pixel_bomb_detected','Image exceeds pixel budget.',413);if((int)($policy['max_width']??0)>0&&(int)$info[0]>(int)$policy['max_width'])throw new Error('image_width_exceeded','Image width exceeds policy.',413);if((int)($policy['max_height']??0)>0&&(int)$info[1]>(int)$policy['max_height'])throw new Error('image_height_exceeded','Image height exceeds policy.',413);$probe+=['width'=>(int)$info[0],'height'=>(int)$info[1],'pixels'=>$pixels];}
        elseif($mime==='application/pdf'){$head=file_get_contents($path,false,null,0,min(1048576,(int)$size));if(!is_string($head)||!str_starts_with($head,'%PDF-')||!str_contains($head,'%%EOF'))throw new Error('pdf_structure_invalid','PDF is malformed/truncated.',422);$pages=preg_match_all('/\/Type\s*\/Page\b/',$head);$pages=max(1,(int)$pages);if((int)($policy['max_pages']??0)>0&&$pages>(int)$policy['max_pages'])throw new Error('pdf_page_limit_exceeded','PDF exceeds page limit.',413);if(preg_match('/\/Encrypt\b/',$head)&&!Utils::bool($policy['allow_encrypted_document']??false))throw new Error('encrypted_document_denied','Encrypted document denied by policy.',415);if(preg_match('/\/JavaScript\b|\/JS\b|\/Launch\b|\/EmbeddedFile\b/i',$head))$probe['active_content_detected']=true;$probe['pages']=$pages;}
        elseif($mime==='application/zip'){$probe+=ArchiveInspector::inspect($path,(int)$policy['max_archive_entries'],(int)$policy['max_archive_depth'],(int)$policy['max_archive_ratio']);}
        else{$external=ToolRunner::probe($path,$mime,$policy);$probe+=$external;}
        return $probe;}
    public static function range(?string $header,int $size,int $maxBytes): array {if($header===null||$header==='')return ['start'=>0,'end'=>$size-1,'length'=>$size,'partial'=>false];if(!preg_match('/^bytes=(\d*)-(\d*)$/',$header,$m))throw new Error('range_invalid','Invalid Range header.',416);$start=$m[1]===''?null:(int)$m[1];$end=$m[2]===''?null:(int)$m[2];if($start===null){$length=min($size,max(1,$end??0));$start=$size-$length;$end=$size-1;}else{$end=$end??($size-1);}if($start<0||$end<$start||$end>=$size||$end-$start+1>$maxBytes)throw new Error('range_not_satisfiable','Requested range is outside policy.',416);return ['start'=>$start,'end'=>$end,'length'=>$end-$start+1,'partial'=>true];}
}

final class ArchiveInspector {
    public static function inspect(string $path,int $maxEntries,int $maxDepth,int $maxRatio): array {if(!class_exists('ZipArchive'))throw new Error('archive_scanner_unavailable','Zip inspection provider unavailable.',503);$zip=new \ZipArchive();if($zip->open($path)!==true)throw new Error('archive_invalid','Archive cannot be opened.',422);$entries=$zip->numFiles;if($entries>$maxEntries){$zip->close();throw new Error('archive_entry_limit','Archive entry limit exceeded.',413);}$compressed=0;$uncompressed=0;$depth=0;for($i=0;$i<$entries;$i++){$stat=$zip->statIndex($i);if(!is_array($stat))continue;$name=(string)($stat['name']??'');if(str_contains($name,'../')||str_starts_with($name,'/')||preg_match('/\.(php|phtml|phar|exe|dll|js|html?|svg)$/i',$name)){$zip->close();throw new Error('archive_entry_denied','Archive contains unsafe entry.',415,['entry'=>Utils::filename($name)]);}$depth=max($depth,substr_count(trim($name,'/'),'/')+1);$compressed+=(int)($stat['comp_size']??0);$uncompressed+=(int)($stat['size']??0);} $zip->close();if($depth>$maxDepth)throw new Error('archive_depth_limit','Archive nesting exceeds policy.',413);$ratio=$compressed>0?$uncompressed/$compressed:($uncompressed>0?INF:1);if($ratio>$maxRatio)throw new Error('decompression_bomb_detected','Archive expansion ratio exceeds policy.',413);return ['archive_entries'=>$entries,'archive_depth'=>$depth,'compressed_bytes'=>$compressed,'uncompressed_bytes'=>$uncompressed,'expansion_ratio'=>$ratio];}
}

final class ToolRunner {
    public static function probe(string $path,string $mime,array $policy): array {return self::call('probe',['path'=>$path,'mime'=>$mime,'limits'=>['duration'=>(int)($policy['max_duration_seconds']??0),'size'=>(int)$policy['max_size_bytes']]]);}
    public static function transform(string $operation,mixed $source,array $specification): array {return self::call('transform',['operation'=>Utils::key($operation,64),'source'=>$source,'specification'=>$specification]);}
    public static function call(string $operation,array $request): array {$provider=function_exists('apply_filters')?apply_filters('scm_sandbox_tool_result',null,$operation,Utils::redact($request)):null;if(!is_array($provider))throw new Error('sandbox_provider_unavailable','Approved sandbox worker unavailable.',503,['operation'=>$operation]);foreach(['passed','worker_id','worker_version','non_root','network_isolated','ephemeral','resource_limits','output'] as $f)if(!array_key_exists($f,$provider))throw new Error('sandbox_attestation_incomplete','Sandbox attestation incomplete.',503,['field'=>$f]);if($provider['passed']!==true||$provider['non_root']!==true||$provider['network_isolated']!==true||$provider['ephemeral']!==true||!is_array($provider['resource_limits'])||!is_array($provider['output']))throw new Error('sandbox_execution_failed','Sandbox worker did not satisfy isolation policy.',422,['operation'=>$operation]);return $provider['output']+['worker'=>['id'=>Utils::text((string)$provider['worker_id'],96),'version'=>Utils::text((string)$provider['worker_version'],64),'non_root'=>true,'network_isolated'=>true,'ephemeral'=>true,'resource_limits'=>$provider['resource_limits']]];}
}

final class ScannerRegistry {
    private static array $scanners=[];
    public static function reset(): void {self::$scanners=[];}
    public static function register(string $id,callable $scanner,array $meta): void {$id=Utils::key($id,64);Utils::requireFields($meta,['version','timeout_seconds','max_depth','capabilities'],'scanner_metadata_incomplete');self::$scanners[$id]=['callback'=>$scanner,'meta'=>$meta];}
    public static function registerWordPressAdapters(): void {if(!function_exists('apply_filters'))return;foreach(['malware','archive','polyglot','decompression_bomb','metadata','technical_safety'] as $id){self::register($id,function($stream,$context)use($id){return apply_filters('scm_'.$id.'_scan_result',null,$stream,$context);},['version'=>(string)apply_filters('scm_'.$id.'_scanner_version','unknown'),'timeout_seconds'=>(int)apply_filters('scm_'.$id.'_scanner_timeout',30),'max_depth'=>(int)apply_filters('scm_'.$id.'_scanner_depth',5),'capabilities'=>[$id]]);}}
    public static function scan($stream,array $required,array $context): array {if(!is_resource($stream))throw new Error('stream_invalid','Invalid scanner stream.',500);$results=[];foreach($required as $id){$id=Utils::key((string)$id,64);if(in_array($id,['hash','magic','mime'],true)){continue;}if(!isset(self::$scanners[$id]))throw new Error('scanner_unavailable','Required scanner unavailable.',503,['scanner'=>$id]);rewind($stream);try{$result=(self::$scanners[$id]['callback'])($stream,$context+self::$scanners[$id]['meta']);}catch(\Throwable $e){throw new Error('scanner_failed','Scanner failed closed.',503,['scanner'=>$id,'exception'=>get_class($e)]);}if(!is_array($result)||($result['passed']??false)!==true)throw new Error('media_scan_failed','Required scan did not pass.',422,['scanner'=>$id,'reason'=>is_array($result)?($result['reason']??'failed'):'invalid_result']);$results[$id]=Utils::redact($result)+['version'=>self::$scanners[$id]['meta']['version']];}rewind($stream);return $results;}
}

final class MetadataPolicy {
    public static function transform(string $mediaClass,array $source,array $policy): array {$result=ToolRunner::transform('metadata-policy',$source,['media_class'=>$mediaClass,'policy'=>$policy['metadata'],'rights'=>$policy['rights']]);foreach(['output_stream','metadata_removed','metadata_preserved'] as $f)if(!array_key_exists($f,$result))throw new Error('metadata_transform_incomplete','Metadata transform result incomplete.',503,['field'=>$f]);if(!is_resource($result['output_stream']))throw new Error('metadata_transform_invalid','Metadata transform output stream invalid.',503);$removed=array_map('strtolower',(array)$result['metadata_removed']);foreach(['gps','location'] as $sensitive)if(($policy['metadata']['strip_location']??true)&&!in_array($sensitive,$removed,true))throw new Error('metadata_privacy_failed','Location metadata was not proven stripped.',422,['field'=>$sensitive]);return $result;}
}

final class SafetySignalService {
    public static function evaluate($stream,array $asset): array {if(!is_resource($stream))throw new Error('stream_invalid','Invalid safety stream.',500);$scanner=self::scanOptional($stream,$asset);$confidence=(float)($scanner['confidence']??0.0);if($confidence<0||$confidence>1)throw new Error('safety_signal_invalid','Safety confidence invalid.',503);$record=['actor_id'=>0,'asset_id'=>$asset['asset_id'],'model_id'=>Utils::text((string)($scanner['model_id']??'technical-signal'),96),'model_version'=>Utils::text((string)($scanner['model_version']??'unknown'),64),'confidence'=>$confidence,'signals'=>(array)($scanner['signals']??[]),'status'=>'pending_review','autonomous_decision'=>false,'created_at'=>Utils::now()];if($confidence>=(float)$asset['policy']['safety']['minimum_confidence']&&!Utils::bool($scanner['requires_review']??false))$record['status']='informational';return RecordStore::put('safety_signal',Utils::id('sig'),$record);}
    private static function scanOptional($stream,array $asset): array {if(!function_exists('apply_filters'))return ['confidence'=>0.0,'signals'=>[],'requires_review'=>true,'model_id'=>'none','model_version'=>'none'];rewind($stream);$r=apply_filters('scm_technical_safety_signal',null,$stream,Utils::redact($asset));rewind($stream);return is_array($r)?$r:['confidence'=>0.0,'signals'=>[],'requires_review'=>true,'model_id'=>'none','model_version'=>'none'];}
    public static function review(string $signalId,int $reviewer,string $decision,string $reason): array {Auth::capability('media_review_safety_signals');$r=RecordStore::get('safety_signal',$signalId);if(!$r)throw new Error('safety_signal_not_found','Safety signal not found.',404);if(!in_array($decision,['accepted','rejected','escalated'],true))throw new Error('safety_decision_invalid','Invalid review decision.',400);$r['status']=$decision;$r['reviewer_id']=$reviewer;$r['review_reason']=Utils::text($reason,500);$r['reviewed_at']=Utils::now();return RecordStore::put('safety_signal',$signalId,$r,(int)$r['version']);}
}
