<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class LegalHoldService {
    public static function place(string $assetId,int $actor,array $input): array {Auth::capability('media_hold');Utils::requireFields($input,['authority','reason','scope','review_at'],'hold_incomplete');$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_hold',['asset'=>$asset,'actor_id'=>$actor,'hold'=>$input],false);if(($decision['hold_allowed']??true)!==true)throw new Error('hold_denied','Owner denied hold.',403);$id=Utils::id('hold');$hold=['actor_id'=>$actor,'hold_id'=>$id,'asset_id'=>$assetId,'authority'=>Utils::text((string)$input['authority'],191),'reason'=>Utils::text((string)$input['reason'],1000),'scope'=>array_values(array_unique(array_map(fn($s)=>Utils::key((string)$s,32),(array)$input['scope']))),'status'=>'active','access_restriction'=>Utils::key((string)($input['access_restriction']??'restricted'),32),'review_at'=>(int)$input['review_at'],'expires_at'=>max(0,(int)($input['expires_at']??0)),'placed_at'=>Utils::now(),'version_number'=>1];$hold=RecordStore::put('hold',$id,$hold);DeliveryService::revokeForAsset($assetId,'legal_hold');Audit::record('legal_hold_placed',['hold_id'=>$id,'asset_id'=>$assetId,'actor_id'=>$actor,'authority'=>$hold['authority']]);return $hold;}
    public static function active(string $assetId): array {return array_values(array_filter(RecordStore::list('hold'),fn($h)=>($h['asset_id']??'')===$assetId&&($h['status']??'')==='active'&&((int)($h['expires_at']??0)===0||(int)$h['expires_at']>Utils::now())));}
    public static function assertNoHold(string $assetId,string $operation): void {$holds=self::active($assetId);if($holds!==[])throw new Error('asset_on_hold','Asset is under legal/security hold.',423,['operation'=>$operation,'hold_ids'=>array_column($holds,'id')]);}
    public static function review(string $holdId,int $actor,string $decision,string $reason): array {Auth::capability('media_hold');$h=RecordStore::get('hold',$holdId);if(!$h)throw new Error('hold_not_found','Hold not found.',404);if(!in_array($decision,['continue','release','escalate'],true))throw new Error('hold_decision_invalid','Invalid hold decision.',400);$h['reviewed_by']=$actor;$h['review_reason']=Utils::text($reason,1000);$h['reviewed_at']=Utils::now();$h['version_number']=(int)$h['version_number']+1;if($decision==='release'){$h['status']='released';$h['released_at']=Utils::now();}elseif($decision==='escalate')$h['status']='escalated';else $h['review_at']=Utils::now()+2592000;return RecordStore::put('hold',$holdId,$h,(int)$h['version']);}
}

final class RetentionService {
    public static function schedule(string $assetId): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$decision=DomainRegistry::decision($asset['owner_domain'],'retention_decision',['asset'=>$asset,'policy'=>$asset['policy']['retention']],false);$now=Utils::now();$ret=$asset['policy']['retention'];$sourceDelete=max($now+(int)$ret['source_seconds'],(int)($decision['source_retain_until']??0));$derivativeDelete=max($now+(int)$ret['derivative_seconds'],(int)($decision['derivative_retain_until']??0));$backupExpiry=max($now+(int)$ret['backup_expiry_seconds'],(int)($decision['backup_expiry_at']??0));$id=hash('sha256',$assetId.'|'.$asset['policy_hash']);$record=['actor_id'=>0,'asset_id'=>$assetId,'retention_class'=>$ret['class'],'status'=>'scheduled','source_delete_at'=>$sourceDelete,'derivative_delete_at'=>$derivativeDelete,'temporary_cleanup_at'=>$now+(int)$ret['temporary_seconds'],'backup_expiry_at'=>$backupExpiry,'decision_version'=>$decision['contract_version'],'created_at'=>$now];return RecordStore::put('retention',$id,$record,(int)(RecordStore::get('retention',$id)['version']??0));}
    public static function run(int $now=0): array {
        $now=$now?:Utils::now();$out=['temporary_cleaned'=>0,'derivatives_expired'=>0,'deletion_requested'=>0,'holds_skipped'=>0];
        foreach(RecordStore::list('retention') as $r){
            if(!in_array(($r['status']??''),['scheduled','pending','derivatives_expired'],true))continue;$assetId=(string)$r['asset_id'];
            if(LegalHoldService::active($assetId)!==[]){$out['holds_skipped']++;continue;}
            if((int)$r['temporary_cleanup_at']<=$now&&!Utils::bool($r['temporary_cleaned']??false)){PartStore::purge($assetId);$r['temporary_cleaned']=true;$out['temporary_cleaned']++;}
            if((int)$r['derivative_delete_at']<=$now&&!Utils::bool($r['derivatives_expired']??false)&&(int)$r['source_delete_at']>$now){DeletionService::expireDerivatives($assetId,'retention-expiry');$r['derivatives_expired']=true;$r['status']='derivatives_expired';$out['derivatives_expired']++;}
            if((int)$r['source_delete_at']<=$now&&!isset($r['deletion_id'])){$request=DeletionService::request($assetId,0,'retention-expiry',['backup_expiry_at'=>$r['backup_expiry_at']]);$r['status']='deletion_requested';$r['deletion_id']=$request['id'];$out['deletion_requested']++;}
            RecordStore::put('retention',(string)$r['id'],$r,(int)$r['version']);
        }
        return $out;
    }

}

final class DeletionService {
    public static function request(string $assetId,int $actor,string $reason,array $context=[]): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);LegalHoldService::assertNoHold($assetId,'delete');if($actor>0&&$actor!==(int)$asset['actor_id'])Auth::capability('media_reprocess');$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_deletion',['asset'=>$asset,'actor_id'=>$actor,'reason'=>$reason,'context'=>Utils::redact($context)]);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner version stale.',409);$id=Utils::id('del');$record=['actor_id'=>$actor,'deletion_id'=>$id,'asset_id'=>$assetId,'reason'=>Utils::key($reason,64),'status'=>'pending_revoke','steps'=>['revoke_grants'=>'pending','purge_cdn'=>'pending','delete_derivatives'=>'pending','delete_source'=>'pending','delete_mappings'=>'pending','backup_ledger'=>'pending','tombstone'=>'pending'],'attempts'=>0,'next_attempt_at'=>Utils::now(),'backup_expiry_at'=>max(Utils::now(),(int)($context['backup_expiry_at']??Utils::now()+2592000)),'created_at'=>Utils::now()];$asset['status']='deletion_pending';$asset['deletion_id']=$id;$asset['deletion_requested_at']=Utils::now();RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);$record=RecordStore::put('deletion',$id,$record);Audit::record('deletion_requested',['deletion_id'=>$id,'asset_id'=>$assetId,'actor_id'=>$actor,'reason'=>$reason]);return $record;}
    public static function expireDerivatives(string $assetId,string $reason): array {
        $asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);LegalHoldService::assertNoHold($assetId,'expire-derivatives');DeliveryService::revokeForAsset($assetId,$reason);
        $maps=array_values(array_filter(RecordStore::list('cdn_mapping'),fn($m)=>($m['asset_id']??'')===$assetId&&($m['status']??'')==='published'));
        if($maps!==[]){if(!CdnRegistry::available())throw new Error('cdn_purge_pending','CDN purge is required before derivative expiry.',503);$purge=CdnRegistry::adapter()->purge(array_column($maps,'version_key'));if(($purge['purged']??false)!==true)throw new Error('cdn_purge_pending','CDN purge was not confirmed.',503);foreach($maps as $m){$m['status']='purged';$m['purged_at']=Utils::now();RecordStore::put('cdn_mapping',(string)$m['id'],$m,(int)$m['version']);}}
        $deleted=[];foreach(DerivativeService::forAsset($assetId) as $d){if(($d['status']??'')==='deleted')continue;if(!ProviderRegistry::store((string)($d['storage']['provider_id']??null))->delete((string)$d['object_key']))throw new Error('derivative_delete_failed','Derivative provider deletion failed.',503,['derivative_id'=>$d['id']]);$d['status']='deleted';$d['deleted_at']=Utils::now();RecordStore::put('derivative',(string)$d['id'],$d,(int)$d['version']);$deleted[]=$d['id'];}
        if(!empty($asset['active_manifest_id'])){$m=RecordStore::get('manifest',(string)$asset['active_manifest_id']);if($m){$m['status']='expired';$m['expired_at']=Utils::now();RecordStore::put('manifest',(string)$m['id'],$m,(int)$m['version']);}}
        $asset['active_manifest_id']=null;$asset['processing_status']='retained_source';$asset['status']='quarantined';$asset['derivatives_expired_at']=Utils::now();RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);Audit::record('derivatives_expired',['asset_id'=>$assetId,'reason'=>$reason,'count'=>count($deleted)]);return ['asset_id'=>$assetId,'deleted_derivatives'=>$deleted,'cdn_mappings'=>count($maps)];
    }
    public static function process(string $deletionId): array {$d=RecordStore::get('deletion',$deletionId);if(!$d)throw new Error('deletion_not_found','Deletion request not found.',404);if(($d['status']??'')==='completed')return $d;if((int)($d['next_attempt_at']??0)>Utils::now())throw new Error('deletion_retry_pending','Deletion retry is not due.',409);$asset=RecordStore::get('asset',(string)$d['asset_id']);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);LegalHoldService::assertNoHold($asset['asset_id'],'delete');$d['attempts']=(int)$d['attempts']+1;
        try{
            if($d['steps']['revoke_grants']!=='complete'){$d['revoked_grants']=DeliveryService::revokeForAsset($asset['asset_id'],'deletion');$d['steps']['revoke_grants']='complete';$d['status']='pending_cdn';$d=self::save($d);}
            if($d['steps']['purge_cdn']!=='complete'){$maps=array_values(array_filter(RecordStore::list('cdn_mapping'),fn($m)=>($m['asset_id']??'')===$asset['asset_id']&&($m['status']??'')==='published'));if($maps!==[]){if(!CdnRegistry::available())throw new Error('cdn_purge_pending','CDN purge adapter unavailable; deletion remains pending.',503);$keys=array_column($maps,'version_key');$purge=CdnRegistry::adapter()->purge($keys);if(($purge['accepted']??false)!==true||($purge['purged']??false)!==true)throw new Error('cdn_purge_pending','CDN purge not confirmed.',503,['result'=>Utils::redact($purge)]);foreach($maps as $m){$m['status']='purged';$m['purged_at']=Utils::now();RecordStore::put('cdn_mapping',(string)$m['id'],$m,(int)$m['version']);}$d['cdn_purge_evidence']=Utils::redact($purge);} $d['steps']['purge_cdn']='complete';$d['status']='pending_derivatives';$d=self::save($d);}
            if($d['steps']['delete_derivatives']!=='complete'){$deleted=[];foreach(DerivativeService::forAsset($asset['asset_id']) as $derivative){if(!ProviderRegistry::store((string)($derivative['storage']['provider_id']??null))->delete((string)$derivative['object_key']))throw new Error('derivative_delete_failed','Derivative provider deletion failed.',503,['derivative_id'=>$derivative['id']]);$derivative['status']='deleted';$derivative['deleted_at']=Utils::now();RecordStore::put('derivative',(string)$derivative['id'],$derivative,(int)$derivative['version']);$deleted[]=$derivative['id'];}$d['deleted_derivatives']=$deleted;$d['steps']['delete_derivatives']='complete';$d['status']='pending_source';$d=self::save($d);}
            if($d['steps']['delete_source']!=='complete'){if(!ProviderRegistry::store((string)($asset['storage']['provider_id']??null))->delete((string)$asset['object_key']))throw new Error('source_delete_failed','Source provider deletion failed.',503);$d['steps']['delete_source']='complete';$d['status']='pending_mappings';$d=self::save($d);}
            if($d['steps']['delete_mappings']!=='complete'){foreach(RecordStore::list('provider_mapping') as $m)if(($m['asset_id']??'')===$asset['asset_id']){RecordStore::delete('provider_mapping',(string)$m['id']);}$d['steps']['delete_mappings']='complete';$d['status']='pending_backup_ledger';$d=self::save($d);}
            if($d['steps']['backup_ledger']!=='complete'){$ledger=['actor_id'=>0,'asset_id'=>$asset['asset_id'],'deletion_id'=>$d['id'],'status'=>'awaiting_backup_expiry','backup_expiry_at'=>$d['backup_expiry_at'],'created_at'=>Utils::now()];RecordStore::put('backup_expiry',Utils::id('bak'),$ledger);$d['steps']['backup_ledger']='complete';$d['status']='pending_tombstone';$d=self::save($d);}
            if($d['steps']['tombstone']!=='complete'){$asset['status']='deleted';$asset['deleted_at']=Utils::now();$asset['deletion_id']=$d['id'];unset($asset['object_key'],$asset['storage']);RecordStore::put('asset',$asset['asset_id'],$asset,(int)$asset['version']);RecordStore::put('tombstone',$asset['asset_id'],['actor_id'=>$d['actor_id'],'asset_id'=>$asset['asset_id'],'owner_domain'=>$asset['owner_domain'],'owner_object'=>$asset['owner_object'],'object_version'=>$asset['object_version'],'policy_hash'=>$asset['policy_hash'],'rights_hash'=>$asset['rights']['policy_hash'],'reason'=>$d['reason'],'status'=>'deleted','deleted_at'=>Utils::now(),'backup_expiry_at'=>$d['backup_expiry_at']]);$d['steps']['tombstone']='complete';$d['status']='completed';$d['completed_at']=Utils::now();$d=self::save($d);Audit::record('deletion_completed',['deletion_id'=>$d['id'],'asset_id'=>$asset['asset_id'],'attempts'=>$d['attempts']]);}
            return $d;
        }catch(\Throwable $e){$d['status']='pending_retry';$d['last_error']=$e instanceof Error?$e->errorCode:'unexpected';$d['next_attempt_at']=Utils::now()+min(3600,2**min(8,(int)$d['attempts'])*15);$d=self::save($d);Audit::record('deletion_pending_retry',['deletion_id'=>$d['id'],'asset_id'=>$asset['asset_id'],'error'=>$d['last_error'],'next_attempt_at'=>$d['next_attempt_at']]);throw $e;}
    }
    private static function save(array $d): array {return RecordStore::put('deletion',(string)$d['id'],$d,(int)$d['version']);}
    public static function reconcile(): array {$result=['completed'=>0,'pending'=>0,'failed'=>0];foreach(RecordStore::list('deletion') as $d){if(($d['status']??'')==='completed'){$result['completed']++;continue;}if((int)($d['next_attempt_at']??0)>Utils::now()){$result['pending']++;continue;}try{self::process((string)$d['id']);$result['completed']++;}catch(\Throwable){$result['failed']++;}}return $result;}
}
