<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class Idempotency {
    public static function claim(string $scope,string $key,string $fingerprint,int $ttl=86400): array {
        $scope=Utils::key($scope,48);$key=Utils::text($key,128);if($scope===''||$key===''||!preg_match('/^[a-f0-9]{64}$/',$fingerprint))throw new Error('idempotency_invalid','Idempotency identity invalid.',400);
        $id=hash('sha256',$scope.'|'.$key);$record=RecordStore::get('idempotency',$id);
        if($record){if(!hash_equals((string)$record['fingerprint'],$fingerprint))throw new Error('idempotency_conflict','Idempotency key reused with different request.',409);if(($record['status']??'')==='completed')return ['replay'=>true,'record'=>$record];if(($record['status']??'')==='claimed'&&(int)($record['expires_at']??0)>Utils::now())throw new Error('idempotency_in_progress','Equivalent request is already in progress.',409);}
        $row=['actor_id'=>Auth::currentUser(),'scope'=>$scope,'fingerprint'=>$fingerprint,'status'=>'claimed','expires_at'=>Utils::now()+$ttl,'claimed_at'=>Utils::now()];
        return ['replay'=>false,'record'=>RecordStore::put('idempotency',$id,$row,$record?(int)$record['version']:0)];
    }
    public static function complete(string $scope,string $key,string $fingerprint,string $resultType,string $resultId,array $result=[]): array {
        $id=hash('sha256',Utils::key($scope,48).'|'.Utils::text($key,128));$record=RecordStore::get('idempotency',$id);if(!$record||!hash_equals((string)$record['fingerprint'],$fingerprint))throw new Error('idempotency_claim_missing','Idempotency claim missing.',409);$record['status']='completed';$record['result_type']=Utils::key($resultType,48);$record['result_id']=Utils::text($resultId,96);$record['result']=$result;$record['completed_at']=Utils::now();return RecordStore::put('idempotency',$id,$record,(int)$record['version']);
    }
    public static function fail(string $scope,string $key,string $fingerprint,string $code): void {$id=hash('sha256',Utils::key($scope,48).'|'.Utils::text($key,128));$r=RecordStore::get('idempotency',$id);if(!$r||!hash_equals((string)$r['fingerprint'],$fingerprint))return;$r['status']='failed';$r['failure_code']=Utils::key($code,64);$r['failed_at']=Utils::now();RecordStore::put('idempotency',$id,$r,(int)$r['version']);}
}

final class QuotaService {
    public static function reserve(string $domain,int $actor,int $bytes,int $jobs,array $limits,array $context=[]): array {
        if($actor<1||$bytes<0||$jobs<0)throw new Error('quota_request_invalid','Quota request invalid.',400);
        $domain=Utils::key($domain,64);$window=(int)floor(Utils::now()/86400);$id=hash('sha256',$domain.'|'.$actor.'|'.$window);$r=RecordStore::get('quota',$id)??['actor_id'=>$actor,'domain'=>$domain,'window'=>$window,'status'=>'active','reserved_bytes'=>0,'used_bytes'=>0,'reserved_jobs'=>0,'used_jobs'=>0,'abuse_score'=>0];
        $storageLimit=max(1,(int)($limits['storage_bytes']??1073741824));$dailyLimit=max(1,(int)($limits['daily_bytes']??1073741824));$jobLimit=max(1,(int)($limits['jobs']??100));$burst=max(1,(int)($limits['burst_bytes']??67108864));
        if($bytes>$burst&&!Utils::bool($context['governed_exception']??false))throw new Error('quota_burst_exceeded','Upload burst exceeds policy.',429);
        if((int)$r['reserved_bytes']+(int)$r['used_bytes']+$bytes>$dailyLimit||(int)$r['used_bytes']+$bytes>$storageLimit||(int)$r['reserved_jobs']+(int)$r['used_jobs']+$jobs>$jobLimit)throw new Error('quota_exceeded','Quota exhausted.',429,['domain'=>$domain]);
        if((int)($r['abuse_score']??0)>=(int)($limits['abuse_block_score']??100))throw new Error('abuse_policy_block','Abuse policy blocked reservation.',403);
        $reservation=Utils::id('qres');$r['reserved_bytes']+=(int)$bytes;$r['reserved_jobs']+=(int)$jobs;$r['reservations'][$reservation]=['bytes'=>$bytes,'jobs'=>$jobs,'status'=>'reserved','created_at'=>Utils::now(),'context'=>Utils::redact($context)];$r=RecordStore::put('quota',$id,$r,(int)($r['version']??0));return ['quota_id'=>$id,'reservation_id'=>$reservation,'version'=>$r['version']];
    }
    public static function settle(string $quotaId,string $reservationId,bool $commit,int $actualBytes=0,int $actualJobs=0): array {
        $r=RecordStore::get('quota',$quotaId);if(!$r||!isset($r['reservations'][$reservationId]))throw new Error('quota_reservation_missing','Quota reservation missing.',409);$res=$r['reservations'][$reservationId];if(($res['status']??'')!=='reserved')return $r;$r['reserved_bytes']=max(0,(int)$r['reserved_bytes']-(int)$res['bytes']);$r['reserved_jobs']=max(0,(int)$r['reserved_jobs']-(int)$res['jobs']);if($commit){$r['used_bytes']+=(int)$actualBytes;$r['used_jobs']+=(int)$actualJobs;$r['reservations'][$reservationId]['status']='committed';}else{$r['reservations'][$reservationId]['status']='released';}$r['reservations'][$reservationId]['settled_at']=Utils::now();return RecordStore::put('quota',$quotaId,$r,(int)$r['version']);
    }
    public static function scoreAbuse(string $domain,int $actor,int $score,string $reason): void {$id=hash('sha256',Utils::key($domain,64).'|'.$actor.'|'.(int)floor(Utils::now()/86400));$r=RecordStore::get('quota',$id)??['actor_id'=>$actor,'domain'=>Utils::key($domain,64),'window'=>(int)floor(Utils::now()/86400),'status'=>'active','reserved_bytes'=>0,'used_bytes'=>0,'reserved_jobs'=>0,'used_jobs'=>0,'abuse_score'=>0];$r['abuse_score']=max(0,(int)$r['abuse_score']+$score);$r['abuse_reasons'][]=['reason'=>Utils::key($reason,64),'score'=>$score,'at'=>Utils::now()];RecordStore::put('quota',$id,$r,(int)($r['version']??0));}
}

final class RateLimiter {
    public static function hit(string $bucket,string $subject,int $limit,int $windowSeconds): void {$bucket=Utils::key($bucket,48);$id=hash('sha256',$bucket.'|'.$subject.'|'.(int)floor(Utils::now()/$windowSeconds));$r=RecordStore::get('rate',$id)??['actor_id'=>Auth::currentUser(),'bucket'=>$bucket,'count'=>0,'status'=>'active','expires_at'=>Utils::now()+$windowSeconds];if((int)$r['count']>=$limit)throw new Error('rate_limited','Rate limit exceeded.',429);$r['count']++;RecordStore::put('rate',$id,$r,(int)($r['version']??0));}
}

final class PartStore {
    public static function put(string $uploadId,int $part,$stream,string $expectedHash): array {
        if($part<1||!is_resource($stream)||!preg_match('/^[a-f0-9]{64}$/',$expectedHash))throw new Error('upload_part_invalid','Upload part invalid.',400);
        $hash=Utils::streamHash($stream);if(!hash_equals($expectedHash,$hash['sha256']))throw new Error('part_checksum_mismatch','Part checksum mismatch.',422);
        $key=hash('sha256','part|'.$uploadId.'|'.$part.'|'.$expectedHash);$stored=ProviderRegistry::store()->putStream($key,$stream,['scope'=>'upload-part','upload_id'=>$uploadId,'part'=>$part]);
        $id=hash('sha256',$uploadId.'|'.$part);$existing=RecordStore::get('upload_part',$id);if($existing&&hash_equals((string)$existing['sha256'],$expectedHash))return $existing;if($existing)throw new Error('part_conflict','Part number already contains different bytes.',409);
        return RecordStore::put('upload_part',$id,['actor_id'=>Auth::currentUser(),'upload_id'=>$uploadId,'part_number'=>$part,'object_key'=>$stored['object_key'],'size'=>$hash['size'],'sha256'=>$expectedHash,'status'=>'stored','created_at'=>Utils::now()]);
    }
    public static function list(string $uploadId): array {$rows=RecordStore::list('upload_part');$rows=array_values(array_filter($rows,fn($r)=>(string)($r['upload_id']??'')===$uploadId));usort($rows,fn($a,$b)=>(int)$a['part_number']<=>(int)$b['part_number']);return $rows;}
    public static function assemble(string $uploadId,int $expectedSize,string $expectedHash,int $maxParts){$parts=self::list($uploadId);if($parts===[]||count($parts)>$maxParts)throw new Error('upload_parts_incomplete','Upload parts incomplete.',409);$out=Utils::tempStream();$ctx=hash_init('sha256');$size=0;$expectedPart=1;foreach($parts as $part){if((int)$part['part_number']!==$expectedPart++)throw new Error('upload_part_gap','Upload part sequence has a gap.',409);$s=ProviderRegistry::store()->openStream((string)$part['object_key']);try{while(!feof($s)){$chunk=fread($s,1048576);if($chunk===false)throw new Error('stream_read_failed','Part read failed.',500);if($chunk==='')continue;$size+=strlen($chunk);if($size>$expectedSize)throw new Error('upload_size_exceeded','Assembled upload exceeds expected size.',422);hash_update($ctx,$chunk);fwrite($out,$chunk);}}finally{fclose($s);}}$hash=hash_final($ctx);if($size!==$expectedSize||!hash_equals($expectedHash,$hash))throw new Error('upload_integrity_failed','Assembled upload integrity failed.',422,['size'=>$size]);rewind($out);return $out;}
    public static function purge(string $uploadId): void {foreach(self::list($uploadId) as $p){ProviderRegistry::store()->delete((string)$p['object_key']);RecordStore::delete('upload_part',(string)$p['id']);}}
}

final class UploadService {
    public static function create(int $actor,array $metadata,array $rawPolicy,string $idempotencyKey,array $quotaLimits=[]): array {
        RuntimeGuard::requireReady(['streaming']);Auth::verifiedUser($actor,'media_upload_create',(string)($rawPolicy['owner_domain']??''));RateLimiter::hit('upload-create',(string)$actor,60,60);
        $policy=Policy::normalize($rawPolicy,true);self::validateMetadata($metadata,$policy);$fingerprint=hash('sha256',Utils::canonicalJson(['actor'=>$actor,'metadata'=>$metadata,'policy_hash'=>$policy['policy_hash']]));$claim=Idempotency::claim('upload-create',$idempotencyKey,$fingerprint);if($claim['replay']){return RecordStore::get('upload',(string)$claim['record']['result_id'])??throw new Error('upload_replay_missing','Replayed upload missing.',500);}
        $ownerContext=['actor_id'=>$actor,'owner_object'=>Utils::text((string)($metadata['owner_object']??''),191),'policy'=>$policy,'metadata'=>Utils::redact($metadata)];$decision=DomainRegistry::decision($policy['owner_domain'],'authorize_upload',$ownerContext);
        $quota=QuotaService::reserve($policy['owner_domain'],$actor,(int)$metadata['size'],1,$quotaLimits+['storage_bytes'=>1073741824,'daily_bytes'=>2147483648,'jobs'=>100,'burst_bytes'=>1073741824],['purpose'=>$policy['purpose'],'governed_exception'=>Utils::bool($metadata['governed_exception']??false)]);
        $id=Utils::id('upl');$credential=Crypto::sign(['type'=>'upload-credential','upload_id'=>$id,'actor_id'=>$actor,'policy_hash'=>$policy['policy_hash'],'object_version'=>(int)$decision['object_version']],min(86400,max(300,(int)($metadata['session_ttl_seconds']??3600))));
        $row=['actor_id'=>$actor,'upload_id'=>$id,'owner_domain'=>$policy['owner_domain'],'owner_object'=>Utils::text((string)$metadata['owner_object'],191),'object_version'=>(int)$decision['object_version'],'declared_name'=>Utils::filename((string)$metadata['name']),'declared_mime'=>strtolower((string)$metadata['mime']),'expected_size'=>(int)$metadata['size'],'expected_sha256'=>strtolower((string)$metadata['sha256']),'media_class'=>$policy['media_class'],'policy'=>$policy,'policy_hash'=>$policy['policy_hash'],'quota'=>$quota,'credential_hash'=>hash('sha256',$credential),'received_size'=>0,'received_parts'=>0,'status'=>'uploading','expires_at'=>Utils::now()+min(86400,max(300,(int)($metadata['session_ttl_seconds']??3600))),'created_at'=>Utils::now()];
        $row=RecordStore::put('upload',$id,$row);Idempotency::complete('upload-create',$idempotencyKey,$fingerprint,'upload',$id,['credential'=>$credential]);Audit::record('upload_session_created',['upload_id'=>$id,'actor_id'=>$actor,'owner_domain'=>$policy['owner_domain'],'expected_size'=>$metadata['size']]);return $row+['upload_credential'=>$credential];
    }
    private static function validateMetadata(array $m,array $p): void {Utils::requireFields($m,['name','mime','size','sha256','owner_object'],'upload_metadata_incomplete');$size=(int)$m['size'];if($size<1||$size>$p['max_size_bytes'])throw new Error('upload_size_invalid','Upload size outside policy.',413);if(!preg_match('/^[a-f0-9]{64}$/i',(string)$m['sha256']))throw new Error('upload_hash_invalid','Expected SHA-256 invalid.',400);if(!in_array(strtolower((string)$m['mime']),$p['allowed_mime_types'],true))throw new Error('declared_mime_denied','Declared MIME not allowed.',415);$ext=strtolower(pathinfo(Utils::filename((string)$m['name']),PATHINFO_EXTENSION));if($p['allowed_extensions']!==[]&&!in_array($ext,$p['allowed_extensions'],true))throw new Error('extension_denied','File extension denied.',415);}
    private static function authenticate(array $upload,int $actor,string $credential): void {if((int)$upload['actor_id']!==$actor)throw new Error('upload_actor_denied','Upload actor mismatch.',403);$claims=Crypto::verify($credential);foreach(['type'=>'upload-credential','upload_id'=>$upload['id'],'actor_id'=>$actor,'policy_hash'=>$upload['policy_hash']] as $k=>$v)if(($claims[$k]??null)!==$v)throw new Error('upload_credential_invalid','Upload credential invalid.',403,['field'=>$k]);if(!hash_equals((string)$upload['credential_hash'],hash('sha256',$credential)))throw new Error('upload_credential_invalid','Upload credential record mismatch.',403);if((int)$upload['expires_at']<=Utils::now())throw new Error('upload_expired','Upload session expired.',410);}
    public static function putPart(string $uploadId,int $actor,int $part,$stream,string $sha256,string $credential): array {RuntimeGuard::requireReady(['streaming']);$upload=RecordStore::get('upload',$uploadId);if(!$upload)throw new Error('upload_not_found','Upload session not found.',404);self::authenticate($upload,$actor,$credential);if(($upload['status']??'')!=='uploading')throw new Error('upload_state_invalid','Upload is not accepting parts.',409);if($part<1||$part>(int)$upload['policy']['max_upload_parts'])throw new Error('part_number_invalid','Part number outside policy.',400);$hash=Utils::streamHash($stream);if($hash['size']>(int)$upload['policy']['max_part_size_bytes'])throw new Error('part_size_exceeded','Part exceeds policy.',413);$stored=PartStore::put($uploadId,$part,$stream,strtolower($sha256));$parts=PartStore::list($uploadId);$upload['received_size']=array_sum(array_map(fn($p)=>(int)$p['size'],$parts));$upload['received_parts']=count($parts);$upload['progress_percent']=(float)min(100.0,round(100*$upload['received_size']/max(1,(int)$upload['expected_size']),2));$upload=RecordStore::put('upload',$uploadId,$upload,(int)$upload['version']);return ['upload_id'=>$uploadId,'part'=>$stored,'received_size'=>$upload['received_size'],'progress_percent'=>$upload['progress_percent']];}
    public static function pause(string $uploadId,int $actor,string $credential): array {$u=RecordStore::get('upload',$uploadId);if(!$u)throw new Error('upload_not_found','Upload not found.',404);self::authenticate($u,$actor,$credential);if(($u['status']??'')!=='uploading')throw new Error('upload_state_invalid','Upload cannot be paused.',409);$u['status']='paused';return RecordStore::put('upload',$uploadId,$u,(int)$u['version']);}
    public static function resume(string $uploadId,int $actor,string $credential): array {$u=RecordStore::get('upload',$uploadId);if(!$u)throw new Error('upload_not_found','Upload not found.',404);self::authenticate($u,$actor,$credential);if(($u['status']??'')!=='paused')throw new Error('upload_state_invalid','Upload cannot be resumed.',409);$u['status']='uploading';return RecordStore::put('upload',$uploadId,$u,(int)$u['version']);}
    public static function abort(string $uploadId,int $actor,string $credential,string $reason): array {$u=RecordStore::get('upload',$uploadId);if(!$u)throw new Error('upload_not_found','Upload not found.',404);self::authenticate($u,$actor,$credential);if(in_array(($u['status']??''),['completed','aborted'],true))return $u;$u['status']='aborted';$u['abort_reason']=Utils::key($reason,64);$u['aborted_at']=Utils::now();$u=RecordStore::put('upload',$uploadId,$u,(int)$u['version']);PartStore::purge($uploadId);QuotaService::settle($u['quota']['quota_id'],$u['quota']['reservation_id'],false);Audit::record('upload_aborted',['upload_id'=>$uploadId,'actor_id'=>$actor,'reason'=>$reason]);return $u;}
    public static function complete(string $uploadId,int $actor,string $credential,string $idempotencyKey): array {RuntimeGuard::requireReady(['streaming']);$u=RecordStore::get('upload',$uploadId);if(!$u)throw new Error('upload_not_found','Upload not found.',404);self::authenticate($u,$actor,$credential);if(($u['status']??'')!=='uploading')throw new Error('upload_state_invalid','Upload cannot be completed.',409);$fingerprint=hash('sha256',$uploadId.'|'.$u['expected_sha256'].'|'.$u['expected_size']);$claim=Idempotency::claim('upload-complete',$idempotencyKey,$fingerprint);if($claim['replay'])return RecordStore::get('asset',(string)$claim['record']['result_id'])??throw new Error('asset_replay_missing','Completed asset missing.',500);
        $stream=PartStore::assemble($uploadId,(int)$u['expected_size'],(string)$u['expected_sha256'],(int)$u['policy']['max_upload_parts']);
        try{$inspection=Validator::inspectStream($stream,(string)$u['declared_name'],(string)$u['declared_mime'],(array)$u['policy']);rewind($stream);$objectKey=hash('sha256','source|'.$u['expected_sha256'].'|'.$u['policy_hash'].'|'.$u['owner_domain'].'|'.$u['owner_object'].'|'.$u['object_version'].'|'.$u['policy']['rights']['policy_hash']);$existing=self::dedupe($objectKey,$u);if($existing){$stored=$existing['storage'];}else{$stored=ProviderRegistry::store()->putStream($objectKey,$stream,['scope'=>'quarantine','privacy_class'=>$u['policy']['privacy_class'],'owner_domain'=>$u['owner_domain'],'policy_hash'=>$u['policy_hash']]);$stored['provider_id']=ProviderRegistry::activeId();}
            $asset=['actor_id'=>$actor,'asset_id'=>$uploadId,'source_upload_id'=>$uploadId,'owner_domain'=>$u['owner_domain'],'owner_object'=>$u['owner_object'],'object_version'=>$u['object_version'],'policy'=>$u['policy'],'policy_hash'=>$u['policy_hash'],'rights'=>$u['policy']['rights'],'privacy_class'=>$u['policy']['privacy_class'],'media_class'=>$u['media_class'],'declared_name'=>$u['declared_name'],'mime'=>$inspection['mime'],'size'=>$inspection['size'],'sha256'=>$inspection['sha256'],'fingerprint'=>$inspection['fingerprint'],'storage'=>$stored,'object_key'=>$stored['object_key'],'status'=>'quarantined','scan_status'=>'pending','processing_status'=>'pending','manifest_version'=>0,'created_at'=>Utils::now()];$asset=RecordStore::put('asset',$uploadId,$asset);$u['status']='completed';$u['completed_at']=Utils::now();RecordStore::put('upload',$uploadId,$u,(int)$u['version']);QuotaService::settle($u['quota']['quota_id'],$u['quota']['reservation_id'],true,(int)$u['expected_size'],1);PartStore::purge($uploadId);Idempotency::complete('upload-complete',$idempotencyKey,$fingerprint,'asset',$uploadId);Audit::record('asset_quarantined',['asset_id'=>$uploadId,'actor_id'=>$actor,'privacy_class'=>$asset['privacy_class'],'sha256'=>$asset['sha256']]);self::emit('scm.asset.quarantined',$asset);return $asset;
        }catch(\Throwable $e){Idempotency::fail('upload-complete',$idempotencyKey,$fingerprint,$e instanceof Error?$e->errorCode:'unexpected');throw $e;}finally{fclose($stream);}
    }
    private static function dedupe(string $objectKey,array $upload): ?array {foreach(RecordStore::list('asset') as $asset){if(($asset['object_key']??'')===$objectKey&&($asset['policy_hash']??'')===$upload['policy_hash']&&($asset['privacy_class']??'')===$upload['policy']['privacy_class']&&($asset['rights']['policy_hash']??'')===$upload['policy']['rights']['policy_hash']&&in_array(($asset['status']??''),['quarantined','ready'],true))return $asset;}return null;}
    private static function emit(string $event,array $payload): void {if(function_exists('do_action'))do_action($event,Utils::redact($payload));}
}
