<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;
final class TransferService {
    public const MAX_FILE_BYTES=1073741824;
    public static function validateEnvelope(array $in): array { foreach(['native_transfer_id','native_transfer_version','sender_user_id','recipient_type','recipient_reference','expected_size','media_class','declared_name'] as $f) if(!isset($in[$f])||$in[$f]==='') throw new Error('transfer_field_missing','Transfer envelope incomplete.',400,['field'=>$f]); $size=(int)$in['expected_size']; if($size<1||$size>self::MAX_FILE_BYTES) throw new Error('transfer_file_size_exceeded','Transfer exceeds the 1 GiB per-file ceiling.',413); $sender=(int)$in['sender_user_id']; if($sender<1) throw new Error('transfer_sender_invalid','Invalid sender.',400); $type=Utils::key((string)$in['recipient_type'],16); if(!in_array($type,['user','group'],true)) throw new Error('transfer_recipient_type_invalid','Invalid recipient type.',400); $ref=(string)$in['recipient_reference']; if($type==='user' && ctype_digit($ref) && (int)$ref===$sender) throw new Error('transfer_self_recipient_invalid','Self transfer is not allowed.',400); return ['native_transfer_id'=>Utils::text((string)$in['native_transfer_id'],191),'native_transfer_version'=>max(1,(int)$in['native_transfer_version']),'sender_user_id'=>$sender,'recipient_type'=>$type,'recipient_ref_hash'=>Utils::hashReference($type.':'.$ref),'expected_size'=>$size,'media_class'=>Utils::key((string)$in['media_class'],32),'declared_name'=>Utils::filename((string)$in['declared_name']),'confidentiality_class'=>Utils::key((string)($in['confidentiality_class']??'confidential'),32)]; }
    public static function assertTransferPolicy(array $p,int $size): void { if(($p['domain']??'')!=='file17'||($p['purpose']??'')!=='verified-user-transfer'||!in_array($p['privacy_class']??'', ['C3','C4','C5'],true)||$size>min(self::MAX_FILE_BYTES,(int)($p['max_size_bytes']??0))) throw new Error('transfer_policy_privacy_invalid','Transfer policy must remain private and File 17-bound.',503); }
    public static function create(array $in,array $policy): array { Utils::requireRuntime(); $e=self::validateEnvelope($in); Auth::assertVerifiedTransferUser($e['sender_user_id'],'transfer_create','file17'); $policy=Policy::validate($policy,true); self::assertTransferPolicy($policy,$e['expected_size']); Auth::domainDecision('file17','authorize_transfer_create',$e); $id=Utils::id('tr'); return RecordStore::put('transfer',$id,$e+['actor_id'=>$e['sender_user_id'],'id'=>$id,'status'=>'pending_upload','created_at'=>Utils::now()]); }
    public static function revoke(string $id,int $actor): void { $t=RecordStore::get('transfer',$id); if(!$t) throw new Error('transfer_not_found','Transfer not found.',404); if((int)$t['sender_user_id']!==$actor) throw new Error('transfer_revoke_denied','Only sender may revoke.',403); Auth::domainDecision('file17','authorize_transfer_revoke',['transfer'=>$t,'actor_id'=>$actor]); $t['status']='revoked'; RecordStore::put('transfer',$id,$t,(int)$t['version']); }
}
