<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class DeliveryService {
    public static function issue(string $assetId,?string $derivativeId,int $actor,string $serviceId,array $audience,array $context,string $operation,array $rangePolicy,string $sessionId,int $ttl=300,int $maxUses=20): string {
        RuntimeGuard::requireReady(['streaming']);Auth::verifiedUser($actor,'media_delivery_issue',$serviceId,['asset_id'=>$assetId]);$asset=self::asset($assetId);$target=self::target($asset,$derivativeId);$operation=Utils::key($operation,32);$serviceId=Utils::key($serviceId,64);$sessionId=Utils::text($sessionId,128);if($serviceId===''||$sessionId==='')throw new Error('delivery_context_incomplete','Service and session identity required.',400);
        RightsPolicy::assert($asset['rights'],$operation,$context+['audience_type'=>$audience['type']??'private']);self::assertDeliverable($asset,$target,$operation);
        $decision=DomainRegistry::decision($asset['owner_domain'],'authorize_delivery',['asset'=>$asset,'derivative'=>$target,'actor_id'=>$actor,'service_id'=>$serviceId,'audience'=>$audience,'context'=>Utils::redact($context),'operation'=>$operation,'session_id'=>$sessionId,'range_policy'=>$rangePolicy]);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner authorization is stale.',409);
        $grantId=Utils::id('gr');$audienceHash=Utils::hashReference(Utils::canonicalJson($audience));$contextHash=Utils::hashReference(Utils::canonicalJson($context));$sessionHash=Utils::hashReference($sessionId);$rangeHash=Utils::hashReference(Utils::canonicalJson($rangePolicy));$claims=['type'=>'delivery-grant','grant_id'=>$grantId,'asset_id'=>$assetId,'derivative_id'=>$derivativeId??'source','actor_id'=>$actor,'service_id'=>$serviceId,'owner_domain'=>$asset['owner_domain'],'owner_object'=>$asset['owner_object'],'object_version'=>(int)$asset['object_version'],'policy_hash'=>$asset['policy_hash'],'rights_hash'=>$asset['rights']['policy_hash'],'audience_hash'=>$audienceHash,'context_hash'=>$contextHash,'session_hash'=>$sessionHash,'operation'=>$operation,'range_hash'=>$rangeHash,'download_mode'=>$operation==='download','target_sha256'=>$target['sha256']];$ttl=min($ttl,(int)$asset['policy']['delivery']['grant_ttl_seconds']);$token=Crypto::sign($claims,$ttl);$record=['actor_id'=>$actor,'grant_id'=>$grantId,'asset_id'=>$assetId,'derivative_id'=>$derivativeId??'source','service_id'=>$serviceId,'status'=>'active','audience_hash'=>$audienceHash,'context_hash'=>$contextHash,'session_hash'=>$sessionHash,'range_hash'=>$rangeHash,'operation'=>$operation,'token_hash'=>hash('sha256',$token),'policy_hash'=>$asset['policy_hash'],'rights_hash'=>$asset['rights']['policy_hash'],'object_version'=>$asset['object_version'],'target_sha256'=>$target['sha256'],'max_uses'=>max(1,min(1000,$maxUses)),'uses'=>0,'expires_at'=>Utils::now()+$ttl,'created_at'=>Utils::now()];RecordStore::put('grant',$grantId,$record);Audit::record('delivery_grant_issued',['grant_id'=>$grantId,'asset_id'=>$assetId,'derivative_id'=>$derivativeId,'actor_id'=>$actor,'service_id'=>$serviceId,'operation'=>$operation,'expires_in'=>$ttl]);return $token;
    }
    public static function serve(string $token,int $actor,string $serviceId,array $audience,array $context,string $sessionId,?string $rangeHeader=null): array {
        RuntimeGuard::requireReady(['streaming']);$claims=Crypto::verify($token);Utils::requireFields($claims,['type','grant_id','asset_id','derivative_id','actor_id','service_id','owner_domain','owner_object','object_version','policy_hash','rights_hash','audience_hash','context_hash','session_hash','operation','range_hash','target_sha256'],'grant_claims_invalid');if($claims['type']!=='delivery-grant')throw new Error('grant_type_invalid','Invalid grant type.',403);
        $grant=RecordStore::get('grant',(string)$claims['grant_id']);if(!$grant||($grant['status']??'')!=='active')throw new Error('grant_revoked','Delivery grant unavailable or revoked.',403);if((int)$grant['expires_at']<=Utils::now())throw new Error('grant_expired','Delivery grant expired.',403);if((int)$grant['uses']>=(int)$grant['max_uses'])throw new Error('grant_use_limit','Delivery grant use limit reached.',403);if(!hash_equals((string)$grant['token_hash'],hash('sha256',$token)))throw new Error('grant_record_mismatch','Delivery grant record mismatch.',403);
        $serviceId=Utils::key($serviceId,64);$sessionHash=Utils::hashReference($sessionId);$audienceHash=Utils::hashReference(Utils::canonicalJson($audience));$contextHash=Utils::hashReference(Utils::canonicalJson($context));foreach(['actor_id'=>$actor,'service_id'=>$serviceId,'audience_hash'=>$audienceHash,'context_hash'=>$contextHash,'session_hash'=>$sessionHash] as $field=>$value){if(($claims[$field]??null)!==$value||($grant[$field]??null)!==$value)throw new Error('grant_binding_mismatch','Delivery grant binding mismatch.',403,['field'=>$field]);}
        Auth::verifiedUser($actor,'media_delivery_consume',$serviceId,['asset_id'=>$claims['asset_id']]);$asset=self::asset((string)$claims['asset_id']);$target=self::target($asset,$claims['derivative_id']==='source'?null:(string)$claims['derivative_id']);self::assertDeliverable($asset,$target,(string)$claims['operation']);foreach(['owner_domain','owner_object','policy_hash'] as $f)if(!hash_equals((string)$claims[$f],(string)$asset[$f]))throw new Error('grant_asset_state_changed','Asset state changed after grant issuance.',403,['field'=>$f]);if((int)$claims['object_version']!==(int)$asset['object_version']||!hash_equals((string)$claims['rights_hash'],(string)$asset['rights']['policy_hash'])||!hash_equals((string)$claims['target_sha256'],(string)$target['sha256']))throw new Error('grant_asset_state_changed','Asset or policy version changed.',403);
        RightsPolicy::assert($asset['rights'],(string)$claims['operation'],$context+['audience_type'=>$audience['type']??'private']);$rangePolicy=['allow_ranges'=>$asset['policy']['delivery']['allow_ranges'],'max_range_bytes'=>$asset['policy']['delivery']['max_range_bytes']];if(!hash_equals((string)$claims['range_hash'],Utils::hashReference(Utils::canonicalJson($rangePolicy))))throw new Error('grant_range_policy_changed','Range policy changed.',403);
        $decision=DomainRegistry::decision($asset['owner_domain'],'authorize_delivery',['asset'=>$asset,'derivative'=>$target,'actor_id'=>$actor,'service_id'=>$serviceId,'audience'=>$audience,'context'=>Utils::redact($context),'operation'=>$claims['operation'],'session_id'=>$sessionId,'grant_id'=>$claims['grant_id'],'range_header'=>$rangeHeader]);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner authorization is stale.',409);
        $range=$rangeHeader!==null&&$rangeHeader!==''?Validator::range($rangeHeader,(int)$target['size'],(int)$asset['policy']['delivery']['max_range_bytes']):['start'=>0,'end'=>(int)$target['size']-1,'length'=>(int)$target['size'],'partial'=>false];if($range['partial']&&!$asset['policy']['delivery']['allow_ranges'])throw new Error('range_denied','Byte ranges are not allowed.',416);
        $stream=ProviderRegistry::store((string)($target['storage']['provider_id']??null))->openStream((string)$target['object_key']);$output=self::sliceStream($stream,$range['start'],$range['length']);fclose($stream);$stats=Utils::streamHash($output);if(!$range['partial']&&!hash_equals((string)$target['sha256'],$stats['sha256'])){fclose($output);IntegrityService::quarantine($asset['asset_id'],'delivery_hash_mismatch');throw new Error('delivery_integrity_failed','Delivery integrity verification failed.',500);}
        $grant['uses']=(int)$grant['uses']+1;$grant['last_used_at']=Utils::now();$grant['last_range']=$range;$grant=RecordStore::put('grant',(string)$grant['id'],$grant,(int)$grant['version']);Audit::record('delivery_grant_consumed',['grant_id'=>$grant['id'],'asset_id'=>$asset['asset_id'],'actor_id'=>$actor,'service_id'=>$serviceId,'range'=>$range]);$download=($claims['operation']==='download');$filename=Utils::filename((string)$asset['declared_name']);return ['stream'=>$output,'status'=>$range['partial']?206:200,'headers'=>self::headers($target,$filename,$download,$range),'range'=>$range,'grant_uses'=>$grant['uses']];
    }
    private static function sliceStream($source,int $start,int $length){$out=Utils::tempStream();rewind($source);if($start>0)fseek($source,$start);$remaining=$length;while($remaining>0&&!feof($source)){$chunk=fread($source,min(1048576,$remaining));if($chunk===false)throw new Error('delivery_read_failed','Delivery read failed.',500);if($chunk==='')break;fwrite($out,$chunk);$remaining-=strlen($chunk);}if($remaining!==0)throw new Error('delivery_range_incomplete','Delivery range incomplete.',500);rewind($out);return $out;}
    private static function headers(array $target,string $filename,bool $download,array $range): array {$headers=['Content-Type'=>(string)($target['mime']??'application/octet-stream'),'Content-Length'=>(string)$range['length'],'Content-Disposition'=>($download?'attachment':'inline').'; filename="'.addcslashes($filename,'"\\').'"; filename*=UTF-8\'\''.rawurlencode($filename),'Cache-Control'=>'private, no-store, max-age=0','Pragma'=>'no-cache','Referrer-Policy'=>'no-referrer','X-Content-Type-Options'=>'nosniff','Content-Security-Policy'=>"default-src 'none'; sandbox",'Cross-Origin-Resource-Policy'=>'same-origin','Accept-Ranges'=>'bytes'];if($range['partial'])$headers['Content-Range']='bytes '.$range['start'].'-'.$range['end'].'/'.$target['size'];return $headers;}
    private static function asset(string $id): array {$a=RecordStore::get('asset',$id);if(!$a)throw new Error('asset_not_found','Asset not found.',404);return $a;}
    private static function target(array $asset,?string $derivativeId): array {if($derivativeId===null)return ['id'=>$asset['asset_id'],'sha256'=>$asset['sha256'],'size'=>$asset['size'],'object_key'=>$asset['object_key'],'storage'=>$asset['storage'],'mime'=>$asset['mime'],'status'=>$asset['status']];$d=RecordStore::get('derivative',$derivativeId);if(!$d||($d['asset_id']??'')!==$asset['asset_id'])throw new Error('derivative_not_found','Derivative not found.',404);return $d+['mime'=>$d['mime']??$asset['mime']];}
    private static function assertDeliverable(array $asset,array $target,string $operation): void {if(($asset['status']??'')!=='ready'||($asset['scan_status']??'')!=='passed'||($asset['processing_status']??'')!=='completed')throw new Error('asset_not_deliverable','Asset has not completed safe processing.',409);if(LegalHoldService::active((string)$asset['asset_id'])!==[])throw new Error('asset_on_hold','Asset delivery is blocked by legal/security hold.',423);if(($target['status']??'')==='deleted'||($target['status']??'')==='quarantined')throw new Error('target_not_deliverable','Target is not deliverable.',409);if($operation==='download'&&!$asset['policy']['delivery']['allow_download'])throw new Error('download_denied','Download is prohibited by policy.',403);}
    public static function revoke(string $grantId,int $actor,string $reason='owner-revoke'): array {$g=RecordStore::get('grant',$grantId);if(!$g)throw new Error('grant_not_found','Grant not found.',404);if(($g['status']??'')==='revoked')return $g;$asset=self::asset((string)$g['asset_id']);if($actor!==(int)$g['actor_id'])Auth::capability('media_reprocess');DomainRegistry::decision($asset['owner_domain'],'authorize_grant_revoke',['asset'=>$asset,'grant'=>$g,'actor_id'=>$actor,'reason'=>$reason]);$g['status']='revoked';$g['revoked_at']=Utils::now();$g['revoked_by']=$actor;$g['revoke_reason']=Utils::key($reason,64);$g=RecordStore::put('grant',$grantId,$g,(int)$g['version']);Audit::record('delivery_grant_revoked',['grant_id'=>$grantId,'asset_id'=>$asset['asset_id'],'actor_id'=>$actor,'reason'=>$reason]);return $g;}
    public static function revokeForAsset(string $assetId,string $reason): int {$count=0;foreach(RecordStore::list('grant') as $g){if(($g['asset_id']??'')===$assetId&&($g['status']??'')==='active'){$g['status']='revoked';$g['revoked_at']=Utils::now();$g['revoke_reason']=Utils::key($reason,64);RecordStore::put('grant',(string)$g['id'],$g,(int)$g['version']);$count++;}}return $count;}
    public static function publishPublic(string $assetId,string $derivativeId): array {$asset=self::asset($assetId);$d=self::target($asset,$derivativeId);if($asset['privacy_class']!=='C1'||!$asset['policy']['delivery']['public_cdn'])throw new Error('public_cdn_denied','Only public policy-approved assets may use CDN.',403);self::assertDeliverable($asset,$d,'view');RightsPolicy::assert($asset['rights'],'view',['territory'=>'GLOBAL','audience_type'=>'public']);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_delivery',['asset'=>$asset,'derivative'=>$d,'actor_id'=>Auth::currentUser(),'service_id'=>'public-cdn','audience'=>['type'=>'public'],'context'=>['territory'=>'GLOBAL','audience_type'=>'public'],'operation'=>'view','session_id'=>'cdn-publication']);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner authorization is stale.',409);$result=CdnRegistry::adapter()->publish(['asset_id'=>$assetId,'derivative_id'=>$derivativeId,'sha256'=>$d['sha256'],'object_key'=>$d['object_key'],'cache_key'=>$assetId.'/'.$derivativeId.'/'.$d['sha256'],'headers'=>['Content-Type'=>$d['mime']??$asset['mime'],'Cache-Control'=>'public, max-age=31536000, immutable','X-Content-Type-Options'=>'nosniff','Cross-Origin-Resource-Policy'=>'same-site','Content-Security-Policy'=>"default-src 'none'; sandbox"]]);if(($result['published']??false)!==true||empty($result['url'])||empty($result['version_key']))throw new Error('cdn_publish_failed','CDN publication failed.',503);$map=['actor_id'=>0,'asset_id'=>$assetId,'derivative_id'=>$derivativeId,'status'=>'published','url'=>Utils::text((string)$result['url'],1000),'version_key'=>Utils::text((string)$result['version_key'],191),'published_at'=>Utils::now()];return RecordStore::put('cdn_mapping',Utils::id('cdn'),$map);}
}

final class IntegrityService {
    public static function sample(string $assetId): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$targets=[['type'=>'source','id'=>$assetId,'key'=>$asset['object_key'],'sha256'=>$asset['sha256'],'size'=>$asset['size']]];foreach(DerivativeService::forAsset($assetId) as $d)$targets[]=['type'=>'derivative','id'=>$d['id'],'key'=>$d['object_key'],'sha256'=>$d['sha256'],'size'=>$d['size']];$results=[];foreach($targets as $t){$s=ProviderRegistry::store()->openStream((string)$t['key']);try{$stats=Utils::streamHash($s);}finally{fclose($s);}$ok=hash_equals((string)$t['sha256'],$stats['sha256'])&&(int)$t['size']===(int)$stats['size'];$results[]=$t+['ok'=>$ok,'checked_at'=>Utils::now()];if(!$ok)self::quarantine($assetId,'bit_rot_detected');}RecordStore::put('integrity_sample',Utils::id('int'),['actor_id'=>0,'asset_id'=>$assetId,'status'=>array_filter($results,fn($r)=>!$r['ok'])?'failed':'passed','results'=>$results,'created_at'=>Utils::now()]);return $results;}
    public static function quarantine(string $assetId,string $reason): void {$asset=RecordStore::get('asset',$assetId);if(!$asset)return;$asset['status']='quarantined';$asset['integrity_status']='failed';$asset['integrity_reason']=Utils::key($reason,64);$asset['quarantined_at']=Utils::now();RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);DeliveryService::revokeForAsset($assetId,$reason);Audit::record('asset_integrity_quarantined',['asset_id'=>$assetId,'reason'=>$reason]);}
}
