<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class LegalHoldService {
    public static function place(string $assetId,int $actor,array $input): array {Auth::capability('media_hold');Auth::assertActor($actor,'manage_options');Utils::requireFields($input,['authority','reason','scope','review_at'],'hold_incomplete');$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$authority=Utils::text((string)$input['authority'],191);$reason=Utils::text((string)$input['reason'],1000);$scope=array_values(array_filter(array_unique(array_map(fn($value)=>Utils::key((string)$value,32),(array)$input['scope']))));$allowed=['delivery','processing','deletion','reprocess','provider_exit','all'];if($authority===''||$reason===''||$scope===[]||array_diff($scope,$allowed)!==[])throw new Error('hold_incomplete','Hold authority, reason and valid scope are required.',400);$now=Utils::now();$reviewAt=(int)$input['review_at'];$expires=max(0,(int)($input['expires_at']??0));if($reviewAt<=$now||($expires>0&&$expires<=$reviewAt))throw new Error('hold_schedule_invalid','Hold review/expiry schedule invalid.',400);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_hold',['asset'=>$asset,'actor_id'=>$actor,'hold'=>Utils::redact($input)],false);if(($decision['hold_allowed']??true)!==true)throw new Error('hold_denied','Owner denied hold.',403);$id=Utils::id('hold');$hold=['actor_id'=>$actor,'hold_id'=>$id,'asset_id'=>$assetId,'authority'=>$authority,'reason'=>$reason,'scope'=>$scope,'status'=>'active','access_restriction'=>Utils::key((string)($input['access_restriction']??'restricted'),32),'review_at'=>$reviewAt,'expires_at'=>$expires,'placed_at'=>$now,'version_number'=>1];$hold=RecordStore::put('hold',$id,$hold);DeliveryService::revokeForAsset($assetId,'legal_hold');Audit::record('legal_hold_placed',['hold_id'=>$id,'asset_id'=>$assetId,'actor_id'=>$actor,'authority'=>$hold['authority']]);return $hold;}
    public static function active(string $assetId,?string $operation=null): array {
    $operation=$operation===null?null:Utils::key($operation,32);
    $aliases=['delete'=>'deletion','deletion'=>'deletion','deliver'=>'delivery','delivery'=>'delivery','process'=>'processing','processing'=>'processing','repair'=>'reprocess','reprocess'=>'reprocess','provider-exit'=>'provider_exit','provider_exit'=>'provider_exit'];
    $scope=$operation===null?null:($aliases[$operation]??$operation);
    return array_values(array_filter(RecordStore::all('hold',0,null,100000),static function($hold)use($assetId,$scope){
        if(($hold['asset_id']??'')!==$assetId||!in_array(($hold['status']??''),['active','escalated'],true))return false;
        if((int)($hold['expires_at']??0)>0&&(int)$hold['expires_at']<=Utils::now())return false;
        if($scope===null)return true;
        $scopes=(array)($hold['scope']??[]);
        return in_array('all',$scopes,true)||in_array($scope,$scopes,true);
    }));
}
    public static function assertNoHold(string $assetId,string $operation): void {
    $holds=self::active($assetId,$operation);
    if($holds!==[])throw new Error('asset_on_hold','Asset is under a scoped legal/security hold.',423,['operation'=>Utils::key($operation,32),'hold_ids'=>array_column($holds,'id')]);
}
    public static function review(string $holdId,int $actor,string $decision,string $reason): array {Auth::capability('media_hold');Auth::assertActor($actor,'manage_options');$hold=RecordStore::get('hold',$holdId);if(!$hold)throw new Error('hold_not_found','Hold not found.',404);if(!in_array(($hold['status']??''),['active','escalated'],true))throw new Error('hold_state_invalid','Hold is not reviewable.',409);if(!in_array($decision,['continue','release','escalate'],true))throw new Error('hold_decision_invalid','Invalid hold decision.',400);$reason=Utils::text($reason,1000);if($reason==='')throw new Error('hold_review_reason_required','Hold review reason is required.',400);$hold['reviewed_by']=$actor;$hold['review_reason']=$reason;$hold['reviewed_at']=Utils::now();$hold['version_number']=(int)$hold['version_number']+1;if($decision==='release'){$hold['status']='released';$hold['released_at']=Utils::now();}elseif($decision==='escalate'){$hold['status']='escalated';$hold['review_at']=Utils::now()+604800;}else{$hold['status']='active';$hold['review_at']=Utils::now()+2592000;}return RecordStore::put('hold',$holdId,$hold,(int)$hold['version']);}
}

final class RetentionService {
    public static function schedule(string $assetId): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$decision=DomainRegistry::decision($asset['owner_domain'],'retention_decision',['asset'=>$asset,'policy'=>$asset['policy']['retention']],false);$now=Utils::now();$ret=$asset['policy']['retention'];$sourceDelete=max($now+(int)$ret['source_seconds'],(int)($decision['source_retain_until']??0));$derivativeDelete=max($now+(int)$ret['derivative_seconds'],(int)($decision['derivative_retain_until']??0));$backupExpiry=max($now+(int)$ret['backup_expiry_seconds'],(int)($decision['backup_expiry_at']??0));$id=hash('sha256',$assetId.'|'.$asset['policy_hash']);$record=['actor_id'=>0,'asset_id'=>$assetId,'retention_class'=>$ret['class'],'status'=>'scheduled','source_delete_at'=>$sourceDelete,'derivative_delete_at'=>$derivativeDelete,'temporary_cleanup_at'=>$now+(int)$ret['temporary_seconds'],'backup_expiry_at'=>$backupExpiry,'decision_version'=>$decision['contract_version'],'created_at'=>$now];return RecordStore::put('retention',$id,$record,(int)(RecordStore::get('retention',$id)['version']??0));}
    public static function run(int $now=0): array {
    $now=$now?:Utils::now();$cleanup=UploadService::cleanupExpired($now);
    $out=['temporary_cleaned'=>(int)$cleanup['parts_purged'],'uploads_expired'=>(int)$cleanup['expired'],'cleanup_failed'=>(int)$cleanup['failed'],'derivatives_expired'=>0,'deletion_requested'=>0,'holds_skipped'=>0];
    foreach(RecordStore::all('retention',0,null,100000) as $retention){
        if(!in_array(($retention['status']??''),['scheduled','pending','derivatives_expired'],true))continue;
        $assetId=(string)$retention['asset_id'];$deletionHeld=LegalHoldService::active($assetId,'deletion')!==[];
        if((int)$retention['derivative_delete_at']<=$now&&!Utils::bool($retention['derivatives_expired']??false)&&(int)$retention['source_delete_at']>$now){
            if($deletionHeld){$out['holds_skipped']++;continue;}
            DeletionService::expireDerivatives($assetId,'retention-expiry');$retention['derivatives_expired']=true;$retention['status']='derivatives_expired';$out['derivatives_expired']++;
        }
        if((int)$retention['source_delete_at']<=$now&&!isset($retention['deletion_id'])){
            if($deletionHeld){$out['holds_skipped']++;continue;}
            $request=DeletionService::request($assetId,0,'retention-expiry',['backup_expiry_at'=>$retention['backup_expiry_at']]);$retention['status']='deletion_requested';$retention['deletion_id']=$request['id'];$out['deletion_requested']++;
        }
        $retention['temporary_cleaned']=true;
        RecordStore::put('retention',(string)$retention['id'],$retention,(int)$retention['version']);
    }
    return $out;
}

}

final class DeletionService {
    public static function request(string $assetId,int $actor,string $reason,array $context=[]): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);if(($asset['status']??'')==='deleted')throw new Error('asset_deleted','Asset is already deleted.',410);if(!empty($asset['deletion_id'])){$existing=RecordStore::get('deletion',(string)$asset['deletion_id']);if($existing&&!in_array(($existing['status']??''),['completed','cancelled'],true))return $existing;}LegalHoldService::assertNoHold($assetId,'delete');if($actor>0){Auth::assertActor($actor,'manage_options');if($actor!==(int)$asset['actor_id'])Auth::capability('media_reprocess');}$reason=Utils::key($reason,64);if($reason==='')throw new Error('deletion_reason_required','Deletion reason required.',400);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_deletion',['asset'=>$asset,'actor_id'=>$actor,'reason'=>$reason,'context'=>Utils::redact($context)]);if((int)$decision['object_version']!==(int)$asset['object_version'])throw new Error('domain_object_version_stale','Owner version stale.',409);$id=Utils::id('del');$now=Utils::now();$backup=max($now,min($now+315360000,(int)($context['backup_expiry_at']??$now+2592000)));$record=['actor_id'=>$actor,'deletion_id'=>$id,'asset_id'=>$assetId,'reason'=>$reason,'status'=>'pending_revoke','steps'=>['revoke_grants'=>'pending','purge_cdn'=>'pending','delete_derivatives'=>'pending','delete_source'=>'pending','delete_mappings'=>'pending','backup_ledger'=>'pending','tombstone'=>'pending'],'attempts'=>0,'next_attempt_at'=>$now,'backup_expiry_at'=>$backup,'created_at'=>$now];$asset['status']='deletion_pending';$asset['deletion_id']=$id;$asset['deletion_requested_at']=$now;RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);try{$record=RecordStore::put('deletion',$id,$record);}catch(\Throwable $exception){$fresh=RecordStore::get('asset',$assetId);if($fresh&&($fresh['deletion_id']??'')===$id){unset($fresh['deletion_id'],$fresh['deletion_requested_at']);$fresh['status']='ready';RecordStore::put('asset',$assetId,$fresh,(int)$fresh['version']);}throw $exception;}Audit::record('deletion_requested',['deletion_id'=>$id,'asset_id'=>$assetId,'actor_id'=>$actor,'reason'=>$reason]);return $record;}
    public static function expireDerivatives(string $assetId,string $reason): array {
        $asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);LegalHoldService::assertNoHold($assetId,'expire-derivatives');DeliveryService::revokeForAsset($assetId,$reason);
        $maps=array_values(array_filter(RecordStore::all('cdn_mapping',0,null,100000),fn($m)=>($m['asset_id']??'')===$assetId&&($m['status']??'')==='published'));
        if($maps!==[]){if(!CdnRegistry::available())throw new Error('cdn_purge_pending','CDN purge is required before derivative expiry.',503);$purge=CdnRegistry::adapter()->purge(array_column($maps,'version_key'));if(($purge['purged']??false)!==true)throw new Error('cdn_purge_pending','CDN purge was not confirmed.',503);foreach($maps as $m){$m['status']='purged';$m['purged_at']=Utils::now();RecordStore::put('cdn_mapping',(string)$m['id'],$m,(int)$m['version']);}}
        $deleted=[];foreach(DerivativeService::forAsset($assetId) as $d){if(($d['status']??'')==='deleted')continue;if(!ProviderRegistry::get((string)($d['storage']['provider_id']??''))->delete((string)$d['object_key']))throw new Error('derivative_delete_failed','Derivative provider deletion failed.',503,['derivative_id'=>$d['id']]);$d['status']='deleted';$d['deleted_at']=Utils::now();RecordStore::put('derivative',(string)$d['id'],$d,(int)$d['version']);$deleted[]=$d['id'];}
        if(!empty($asset['active_manifest_id'])){$m=RecordStore::get('manifest',(string)$asset['active_manifest_id']);if($m){$m['status']='expired';$m['expired_at']=Utils::now();RecordStore::put('manifest',(string)$m['id'],$m,(int)$m['version']);}}
        $asset['active_manifest_id']=null;$asset['processing_status']='retained_source';$asset['status']='quarantined';$asset['derivatives_expired_at']=Utils::now();RecordStore::put('asset',$assetId,$asset,(int)$asset['version']);Audit::record('derivatives_expired',['asset_id'=>$assetId,'reason'=>$reason,'count'=>count($deleted)]);return ['asset_id'=>$assetId,'deleted_derivatives'=>$deleted,'cdn_mappings'=>count($maps)];
    }
    public static function process(string $deletionId): array {$d=RecordStore::get('deletion',$deletionId);if(!$d)throw new Error('deletion_not_found','Deletion request not found.',404);if(($d['status']??'')==='completed')return $d;if((int)($d['next_attempt_at']??0)>Utils::now())throw new Error('deletion_retry_pending','Deletion retry is not due.',409);$asset=RecordStore::get('asset',(string)$d['asset_id']);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);LegalHoldService::assertNoHold($asset['asset_id'],'delete');$d['attempts']=(int)$d['attempts']+1;
        try{
            if($d['steps']['revoke_grants']!=='complete'){$d['revoked_grants']=DeliveryService::revokeForAsset($asset['asset_id'],'deletion');$d['steps']['revoke_grants']='complete';$d['status']='pending_cdn';$d=self::save($d);}
            if($d['steps']['purge_cdn']!=='complete'){$maps=array_values(array_filter(RecordStore::all('cdn_mapping',0,null,100000),fn($m)=>($m['asset_id']??'')===$asset['asset_id']&&($m['status']??'')==='published'));if($maps!==[]){if(!CdnRegistry::available())throw new Error('cdn_purge_pending','CDN purge adapter unavailable; deletion remains pending.',503);$keys=array_column($maps,'version_key');$purge=CdnRegistry::adapter()->purge($keys);if(($purge['accepted']??false)!==true||($purge['purged']??false)!==true)throw new Error('cdn_purge_pending','CDN purge not confirmed.',503,['result'=>Utils::redact($purge)]);foreach($maps as $m){$m['status']='purged';$m['purged_at']=Utils::now();RecordStore::put('cdn_mapping',(string)$m['id'],$m,(int)$m['version']);}$d['cdn_purge_evidence']=Utils::redact($purge);} $d['steps']['purge_cdn']='complete';$d['status']='pending_derivatives';$d=self::save($d);}
            if($d['steps']['delete_derivatives']!=='complete'){$deleted=[];foreach(DerivativeService::forAsset($asset['asset_id']) as $derivative){if(($derivative['status']??'')==='deleted')continue;if(!ProviderRegistry::get((string)($derivative['storage']['provider_id']??''))->delete((string)$derivative['object_key']))throw new Error('derivative_delete_failed','Derivative provider deletion failed.',503,['derivative_id'=>$derivative['id']]);$derivative['status']='deleted';$derivative['deleted_at']=Utils::now();RecordStore::put('derivative',(string)$derivative['id'],$derivative,(int)$derivative['version']);$deleted[]=$derivative['id'];}$d['deleted_derivatives']=$deleted;$d['steps']['delete_derivatives']='complete';$d['status']='pending_source';$d=self::save($d);}
            if($d['steps']['delete_source']!=='complete'){if(!ProviderRegistry::get((string)($asset['storage']['provider_id']??''))->delete((string)$asset['object_key']))throw new Error('source_delete_failed','Source provider deletion failed.',503);$d['steps']['delete_source']='complete';$d['status']='pending_mappings';$d=self::save($d);}
            if($d['steps']['delete_mappings']!=='complete'){foreach(RecordStore::all('provider_mapping',0,null,100000) as $m)if(($m['asset_id']??'')===$asset['asset_id']){RecordStore::delete('provider_mapping',(string)$m['id']);}$d['steps']['delete_mappings']='complete';$d['status']='pending_backup_ledger';$d=self::save($d);}
            if($d['steps']['backup_ledger']!=='complete'){$ledger=['actor_id'=>0,'asset_id'=>$asset['asset_id'],'deletion_id'=>$d['id'],'status'=>'awaiting_backup_expiry','backup_expiry_at'=>$d['backup_expiry_at'],'created_at'=>Utils::now()];$ledgerId=hash('sha256',$d['id'].'|backup-expiry');$existingLedger=RecordStore::get('backup_expiry',$ledgerId);RecordStore::put('backup_expiry',$ledgerId,$ledger,$existingLedger?(int)$existingLedger['version']:0);$d['steps']['backup_ledger']='complete';$d['status']='pending_tombstone';$d=self::save($d);}
            if($d['steps']['tombstone']!=='complete'){$asset['status']='deleted';$asset['deleted_at']=Utils::now();$asset['deletion_id']=$d['id'];unset($asset['object_key'],$asset['storage']);RecordStore::put('asset',$asset['asset_id'],$asset,(int)$asset['version']);$existingTombstone=RecordStore::get('tombstone',$asset['asset_id']);RecordStore::put('tombstone',$asset['asset_id'],['actor_id'=>$d['actor_id'],'asset_id'=>$asset['asset_id'],'owner_domain'=>$asset['owner_domain'],'owner_object'=>$asset['owner_object'],'object_version'=>$asset['object_version'],'policy_hash'=>$asset['policy_hash'],'rights_hash'=>$asset['rights']['policy_hash'],'reason'=>$d['reason'],'status'=>'deleted','deleted_at'=>Utils::now(),'backup_expiry_at'=>$d['backup_expiry_at']],$existingTombstone?(int)$existingTombstone['version']:0);$d['steps']['tombstone']='complete';$d['status']='completed';$d['completed_at']=Utils::now();$d=self::save($d);Audit::record('deletion_completed',['deletion_id'=>$d['id'],'asset_id'=>$asset['asset_id'],'attempts'=>$d['attempts']]);}
            return $d;
        }catch(\Throwable $e){$d['status']='pending_retry';$d['last_error']=$e instanceof Error?$e->errorCode:'unexpected';$d['next_attempt_at']=Utils::now()+min(3600,2**min(8,(int)$d['attempts'])*15);$d=self::save($d);Audit::record('deletion_pending_retry',['deletion_id'=>$d['id'],'asset_id'=>$asset['asset_id'],'error'=>$d['last_error'],'next_attempt_at'=>$d['next_attempt_at']]);throw $e;}
    }
    private static function save(array $d): array {return RecordStore::put('deletion',(string)$d['id'],$d,(int)$d['version']);}
    public static function reconcile(): array {$result=['completed'=>0,'pending'=>0,'failed'=>0];foreach(RecordStore::all('deletion',0,null,100000) as $d){if(($d['status']??'')==='completed'){$result['completed']++;continue;}if((int)($d['next_attempt_at']??0)>Utils::now()){$result['pending']++;continue;}try{self::process((string)$d['id']);$result['completed']++;}catch(\Throwable){$result['failed']++;}}return $result;}
}
