<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;

final class ProviderExitService {
    public static function plan(string $sourceProvider,string $targetProvider,int $actor): array {Auth::capability('media_manage_providers');$source=ProviderRegistry::store($sourceProvider);$target=ProviderRegistry::store($targetProvider);foreach(['copy','delete','streaming'] as $cap){if(($source->capabilities()[$cap]??false)!==true||($target->capabilities()[$cap]??false)!==true)throw new Error('provider_exit_capability_missing','Provider exit capability missing.',503,['capability'=>$cap]);}$id=Utils::id('pex');$items=[];foreach(RecordStore::list('asset') as $a){if(($a['status']??'')==='deleted')continue;if(($a['storage']['provider_id']??ProviderRegistry::activeId())!==$sourceProvider)continue;$items[]=['type'=>'asset','id'=>$a['id'],'object_key'=>$a['object_key'],'sha256'=>$a['sha256'],'size'=>$a['size'],'status'=>'pending'];foreach(DerivativeService::forAsset((string)$a['id']) as $d)$items[]=['type'=>'derivative','id'=>$d['id'],'asset_id'=>$a['id'],'object_key'=>$d['object_key'],'sha256'=>$d['sha256'],'size'=>$d['size'],'status'=>'pending'];}$record=['actor_id'=>$actor,'exit_id'=>$id,'source_provider'=>$sourceProvider,'target_provider'=>$targetProvider,'status'=>'planned','items'=>$items,'copied'=>0,'verified'=>0,'switched'=>0,'purged'=>0,'created_at'=>Utils::now()];return RecordStore::put('provider_exit',$id,$record);}
    public static function copy(string $exitId): array {$p=RecordStore::get('provider_exit',$exitId);if(!$p)throw new Error('provider_exit_not_found','Provider exit plan not found.',404);$source=ProviderRegistry::store((string)$p['source_provider']);$target=ProviderRegistry::store((string)$p['target_provider']);foreach($p['items'] as &$item){if(in_array($item['status'],['copied','verified','switched','purged'],true))continue;$targetKey=hash('sha256','migration|'.$p['target_provider'].'|'.$item['object_key'].'|'.$item['sha256']);$stored=$source->copyTo((string)$item['object_key'],$target,$targetKey);$stream=$target->openStream($targetKey);try{$stats=Utils::streamHash($stream);}finally{fclose($stream);}if(!hash_equals((string)$item['sha256'],$stats['sha256'])||(int)$item['size']!==(int)$stats['size'])throw new Error('provider_exit_integrity_failed','Copied object integrity failed.',500,['id'=>$item['id']]);$item['target_key']=$targetKey;$item['target_storage']=$stored+['provider_id'=>$p['target_provider']];$item['status']='verified';$p['copied']++;$p['verified']++;}unset($item);$p['status']='verified';return RecordStore::put('provider_exit',$exitId,$p,(int)$p['version']);}
    public static function shadowVerify(string $exitId): array {$p=RecordStore::get('provider_exit',$exitId);if(!$p||($p['status']??'')!=='verified')throw new Error('provider_exit_not_verified','Provider exit is not verified.',409);foreach($p['items'] as $item){$target=ProviderRegistry::store((string)$p['target_provider']);$stream=$target->openStream((string)$item['target_key']);try{$stats=Utils::streamHash($stream);}finally{fclose($stream);}if(!hash_equals((string)$item['sha256'],$stats['sha256']))throw new Error('provider_shadow_mismatch','Shadow delivery integrity mismatch.',500,['id'=>$item['id']]);}$p['status']='shadow_verified';$p['shadow_verified_at']=Utils::now();return RecordStore::put('provider_exit',$exitId,$p,(int)$p['version']);}
    public static function switch(string $exitId): array {$p=RecordStore::get('provider_exit',$exitId);if(!$p||($p['status']??'')!=='shadow_verified')throw new Error('provider_exit_not_ready','Provider exit switch is not ready.',409);foreach($p['items'] as &$item){$type=$item['type']==='asset'?'asset':'derivative';$record=RecordStore::get($type,(string)$item['id']);if(!$record)throw new Error('provider_exit_record_missing','Migrated record missing.',500,['id'=>$item['id']]);$record['previous_storage']=$record['storage']??null;$record['previous_object_key']=$record['object_key']??null;$record['storage']=$item['target_storage'];$record['object_key']=$item['target_key'];$record['provider_migrated_at']=Utils::now();RecordStore::put($type,(string)$record['id'],$record,(int)$record['version']);$item['status']='switched';$p['switched']++;}unset($item);ProviderRegistry::activate((string)$p['target_provider']);$p['status']='switched';$p['switched_at']=Utils::now();return RecordStore::put('provider_exit',$exitId,$p,(int)$p['version']);}
    public static function rollback(string $exitId,int $actor,string $reason): array {Auth::capability('media_manage_providers');$p=RecordStore::get('provider_exit',$exitId);if(!$p||!in_array(($p['status']??''),['switched','purge_pending'],true))throw new Error('provider_exit_rollback_unavailable','Provider exit cannot be rolled back.',409);foreach($p['items'] as $item){if(($item['status']??'')!=='switched')continue;$type=$item['type']==='asset'?'asset':'derivative';$r=RecordStore::get($type,(string)$item['id']);if(!$r||empty($r['previous_object_key']))throw new Error('provider_exit_rollback_missing','Previous provider mapping missing.',500);$r['object_key']=$r['previous_object_key'];$r['storage']=$r['previous_storage'];$r['provider_rollback_at']=Utils::now();RecordStore::put($type,(string)$r['id'],$r,(int)$r['version']);}ProviderRegistry::activate((string)$p['source_provider']);$p['status']='rolled_back';$p['rollback_by']=$actor;$p['rollback_reason']=Utils::text($reason,500);$p['rolled_back_at']=Utils::now();return RecordStore::put('provider_exit',$exitId,$p,(int)$p['version']);}
    public static function purgeSource(string $exitId): array {$p=RecordStore::get('provider_exit',$exitId);if(!$p||($p['status']??'')!=='switched')throw new Error('provider_exit_not_switched','Provider exit is not switched.',409);$source=ProviderRegistry::store((string)$p['source_provider']);foreach($p['items'] as &$item){if(($item['status']??'')!=='switched')continue;if(!$source->delete((string)$item['object_key']))throw new Error('provider_source_purge_failed','Source provider purge failed.',503,['id'=>$item['id']]);$item['status']='purged';$p['purged']++;}unset($item);$p['status']='completed';$p['credentials_revocation_required']=true;$p['completed_at']=Utils::now();return RecordStore::put('provider_exit',$exitId,$p,(int)$p['version']);}
}

final class KeyRotationService {
    public static function rotateAll(int $actor): array {
        Auth::capability('media_manage_providers');Keyring::assertReady();$active=Keyring::activeId();$result=['active_key_id'=>$active,'rotated'=>0,'failed'=>0,'groups'=>0];
        $groups=[];
        foreach(RecordStore::list('asset') as $r){if(($r['status']??'')==='deleted'||empty($r['object_key'])||($r['storage']['key_id']??'')===$active)continue;$groups[($r['storage']['provider_id']??ProviderRegistry::activeId()).'|'.$r['object_key']][]=['type'=>'asset','record'=>$r];}
        foreach(RecordStore::list('derivative') as $r){if(($r['status']??'')==='deleted'||empty($r['object_key'])||($r['storage']['key_id']??'')===$active)continue;$groups[($r['storage']['provider_id']??ProviderRegistry::activeId()).'|'.$r['object_key']][]=['type'=>'derivative','record'=>$r];}
        foreach($groups as $group){$first=$group[0]['record'];$providerId=(string)($first['storage']['provider_id']??ProviderRegistry::activeId());$oldKey=(string)$first['object_key'];try{$source=ProviderRegistry::store($providerId)->openStream($oldKey);$newKey=hash('sha256','rekey|'.$oldKey.'|'.$active.'|'.$first['sha256']);try{$stored=ProviderRegistry::store($providerId)->putStream($newKey,$source,['scope'=>'key-rotation','source_key'=>$oldKey]);}finally{fclose($source);}if(!hash_equals((string)$first['sha256'],(string)$stored['sha256']))throw new Error('key_rotation_integrity_failed','Re-encrypted object integrity failed.',500);$stored['provider_id']=$providerId;foreach($group as $entry){$r=$entry['record'];$oldKeyId=$r['storage']['key_id']??null;$r['object_key']=$newKey;$r['storage']=$stored;$r['previous_key_id']=$oldKeyId;$r['rotated_at']=Utils::now();RecordStore::put($entry['type'],(string)$r['id'],$r,(int)$r['version']);$result['rotated']++;}if(!ProviderRegistry::store($providerId)->delete($oldKey))throw new Error('key_rotation_cleanup_failed','Old encrypted object could not be deleted.',503);$result['groups']++;}catch(\Throwable $e){$result['failed']++;Observability::alert('critical','key_rotation_failed',['object_key_hash'=>hash('sha256',$oldKey),'exception'=>get_class($e)]);}}
        Audit::record('key_rotation_completed',$result+['actor_id'=>$actor]);return $result;
    }
}

final class CostService {
    public static function record(string $assetId,string $provider,string $purpose,array $units,array $rates): array {$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$cost=0.0;foreach($units as $name=>$value)$cost+=(float)$value*(float)($rates[$name]??0);$id=Utils::id('cost');$row=['actor_id'=>0,'cost_id'=>$id,'asset_id'=>$assetId,'owner_domain'=>$asset['owner_domain'],'purpose'=>Utils::key($purpose,64),'provider'=>Utils::key($provider,64),'units'=>$units,'rates'=>$rates,'cost'=>round($cost,8),'currency'=>'USD','status'=>'recorded','created_at'=>Utils::now()];$row=RecordStore::put('cost',$id,$row);self::checkBudget($asset['owner_domain'],$row);return $row;}
    public static function setBudget(string $domain,string $period,float $limit,int $actor): array {Auth::capability('media_manage_providers');$id=hash('sha256',$domain.'|'.$period);return RecordStore::put('budget',$id,['actor_id'=>$actor,'domain'=>Utils::key($domain,64),'period'=>Utils::key($period,32),'limit'=>$limit,'status'=>'active','created_at'=>Utils::now()],(int)(RecordStore::get('budget',$id)['version']??0));}
    private static function checkBudget(string $domain,array $row): void {$period=gmdate('Y-m');$b=RecordStore::get('budget',hash('sha256',$domain.'|'.$period));if(!$b)return;$spent=array_sum(array_map(fn($c)=>($c['owner_domain']??'')===$domain&&gmdate('Y-m',(int)$c['created_at'])===$period?(float)$c['cost']:0,RecordStore::list('cost')));if($spent>(float)$b['limit']){Audit::record('budget_threshold_exceeded',['domain'=>$domain,'spent'=>$spent,'limit'=>$b['limit'],'cost_id'=>$row['id']]);if(function_exists('do_action'))do_action('scm.budget.threshold',['domain'=>$domain,'spent'=>$spent,'limit'=>$b['limit']]);}}
    public static function reconcile(string $provider,array $invoice): array {$calculated=array_sum(array_map(fn($c)=>($c['provider']??'')===Utils::key($provider,64)?(float)$c['cost']:0,RecordStore::list('cost')));$reported=(float)($invoice['total']??0);$delta=abs($calculated-$reported);$result=['actor_id'=>0,'provider'=>Utils::key($provider,64),'calculated'=>$calculated,'reported'=>$reported,'delta'=>$delta,'status'=>$delta<=(float)($invoice['tolerance']??0.01)?'reconciled':'mismatch','created_at'=>Utils::now()];return RecordStore::put('invoice_reconciliation',Utils::id('inv'),$result);}
}

final class RepairService {
    public static function preview(string $assetId,string $reason,array $targetKinds,array $preset,int $actor): array {Auth::capability('media_reprocess');$asset=RecordStore::get('asset',$assetId);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$decision=DomainRegistry::decision($asset['owner_domain'],'authorize_reprocess',['asset'=>$asset,'actor_id'=>$actor,'reason'=>$reason,'target_kinds'=>$targetKinds,'preset'=>$preset]);$id=Utils::id('repair');$row=['actor_id'=>$actor,'repair_id'=>$id,'asset_id'=>$assetId,'reason'=>Utils::text($reason,1000),'target_kinds'=>array_values(array_unique(array_map(fn($k)=>Utils::key((string)$k,64),$targetKinds))),'preset'=>$preset,'owner_object_version'=>$decision['object_version'],'previous_manifest_id'=>$asset['active_manifest_id']??null,'status'=>'preview','created_at'=>Utils::now()];return RecordStore::put('repair',$id,$row);}
    public static function execute(string $repairId,string $idempotencyKey): array {$r=RecordStore::get('repair',$repairId);if(!$r||($r['status']??'')!=='preview')throw new Error('repair_not_ready','Repair is not ready.',409);$fingerprint=hash('sha256',Utils::canonicalJson($r));$claim=Idempotency::claim('repair',$idempotencyKey,$fingerprint);if($claim['replay'])return RecordStore::get('repair',$repairId)??$r;$asset=RecordStore::get('asset',(string)$r['asset_id']);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$oldManifest=$asset['active_manifest_id']??null;$asset['status']='quarantined';$asset['processing_status']='pending';$asset['job_graph']=[];RecordStore::put('asset',(string)$asset['id'],$asset,(int)$asset['version']);try{ProcessingService::start((string)$asset['id']);$updated=ProcessingService::execute((string)$asset['id'],'repair-worker');$r['status']='completed';$r['new_manifest_id']=$updated['active_manifest_id']??null;$r['completed_at']=Utils::now();$r=RecordStore::put('repair',$repairId,$r,(int)$r['version']);Idempotency::complete('repair',$idempotencyKey,$fingerprint,'repair',$repairId);return $r;}catch(\Throwable $e){$asset=RecordStore::get('asset',(string)$asset['id'])??$asset;if($oldManifest){$asset['active_manifest_id']=$oldManifest;$asset['status']='ready';$asset['processing_status']='completed';RecordStore::put('asset',(string)$asset['id'],$asset,(int)$asset['version']);}$r['status']='failed';$r['error']=$e instanceof Error?$e->errorCode:'unexpected';$r['last_valid_preserved']=$oldManifest!==null;RecordStore::put('repair',$repairId,$r,(int)$r['version']);Idempotency::fail('repair',$idempotencyKey,$fingerprint,$r['error']);throw $e;}}
    public static function rollback(string $repairId,int $actor): array {Auth::capability('media_reprocess');$r=RecordStore::get('repair',$repairId);if(!$r||empty($r['previous_manifest_id']))throw new Error('repair_rollback_unavailable','Repair rollback unavailable.',409);$asset=RecordStore::get('asset',(string)$r['asset_id']);if(!$asset)throw new Error('asset_not_found','Asset not found.',404);$asset['active_manifest_id']=$r['previous_manifest_id'];$asset['status']='ready';$asset['processing_status']='completed';RecordStore::put('asset',(string)$asset['id'],$asset,(int)$asset['version']);$r['status']='rolled_back';$r['rolled_back_by']=$actor;$r['rolled_back_at']=Utils::now();return RecordStore::put('repair',$repairId,$r,(int)$r['version']);}
}

final class RestoreService {
    public static function start(int $actor,array $inventory): array {Auth::capability('media_manage_providers');Utils::requireFields($inventory,['database_snapshot','object_inventory','keyring_version','policy_snapshot','manifest_snapshot','tombstone_snapshot'],'restore_inventory_incomplete');$id=Utils::id('rst');$row=['actor_id'=>$actor,'restore_id'=>$id,'inventory'=>Utils::redact($inventory),'status'=>'rebuilding','checks'=>[],'created_at'=>Utils::now()];return RecordStore::put('restore',$id,$row);}
    public static function reconcile(string $restoreId): array {$r=RecordStore::get('restore',$restoreId);if(!$r)throw new Error('restore_not_found','Restore not found.',404);$checks=['schema'=>Schema::ready(),'keyring'=>self::check(fn()=>Keyring::assertReady()),'provider'=>self::check(fn()=>ProviderRegistry::store()),'tombstones'=>self::tombstones(),'rights'=>self::rights(),'manifests'=>self::manifests(),'integrity'=>self::integrity()];$r['checks']=$checks;$r['status']=in_array(false,$checks,true)?'blocked':'reconciled';$r['reconciled_at']=Utils::now();return RecordStore::put('restore',$restoreId,$r,(int)$r['version']);}
    private static function check(callable $f): bool {try{$f();return true;}catch(\Throwable){return false;}}
    private static function tombstones(): bool {foreach(RecordStore::list('tombstone') as $t){$a=RecordStore::get('asset',(string)$t['asset_id']);if($a&&($a['status']??'')!=='deleted')return false;}return true;}
    private static function rights(): bool {foreach(RecordStore::list('asset') as $a){if(($a['status']??'')==='deleted')continue;try{RightsPolicy::assert($a['rights'],'view',['territory'=>'GLOBAL','audience_type'=>'private']);}catch(Error $e){if($e->errorCode==='rights_operation_denied')continue;return false;}}return true;}
    private static function manifests(): bool {foreach(RecordStore::list('asset') as $a){if(($a['status']??'')==='ready'&&empty($a['active_manifest_id']))return false;}return true;}
    private static function integrity(): bool {foreach(RecordStore::list('asset') as $a){if(($a['status']??'')==='deleted')continue;try{IntegrityService::sample((string)$a['id']);}catch(\Throwable){return false;}}return true;}
    public static function authorizeServe(string $restoreId): void {$r=RecordStore::get('restore',$restoreId);if(!$r||($r['status']??'')!=='reconciled')throw new Error('restore_gate_blocked','Restore reconciliation has not passed.',503);$r['status']='serve_authorized';$r['serve_authorized_at']=Utils::now();RecordStore::put('restore',$restoreId,$r,(int)$r['version']);}
}

final class Observability {
    public static function metric(string $name,float $value,array $labels=[]): array {$name=Utils::key($name,96);$safe=[];foreach($labels as $k=>$v)$safe[Utils::key((string)$k,48)]=Utils::text((string)$v,96);return RecordStore::put('metric',Utils::id('met'),['actor_id'=>0,'metric'=>$name,'value'=>$value,'labels'=>$safe,'status'=>'recorded','created_at'=>Utils::now()]);}
    public static function trace(string $operation,string $traceId,string $spanId,array $context=[]): array {return RecordStore::put('trace',Utils::id('trc'),['actor_id'=>Auth::currentUser(),'operation'=>Utils::key($operation,96),'trace_id'=>Utils::text($traceId,96),'span_id'=>Utils::text($spanId,96),'context'=>Utils::redact($context),'status'=>'recorded','created_at'=>Utils::now()]);}
    public static function health(): array {$providers=ProviderRegistry::health();$queued=count(array_filter(RecordStore::list('job'),fn($j)=>in_array(($j['status']??''),['queued','retry','leased'],true)));$oldest=0;foreach(RecordStore::list('job') as $j)if(in_array(($j['status']??''),['queued','retry'],true))$oldest=max($oldest,Utils::now()-(int)$j['created_at']);$dead=count(RecordStore::list('job',0,'dead_letter'));$pendingDeletion=count(array_filter(RecordStore::list('deletion'),fn($d)=>($d['status']??'')!=='completed'));$status=RuntimeGuard::enabled()&&Schema::ready()&&$providers!==[]&&!in_array(false,array_map(fn($p)=>($p['healthy']??false)===true,$providers),true)?'ready':'disabled_or_degraded';return ['status'=>$status,'runtime_enabled'=>RuntimeGuard::enabled(),'schema_ready'=>Schema::ready(),'providers'=>$providers,'queue_depth'=>$queued,'oldest_queue_age_seconds'=>$oldest,'dead_letters'=>$dead,'pending_deletions'=>$pendingDeletion,'audit_chain'=>Audit::verifyChain(),'manifest'=>IntegrationRegistry::manifest(),'runbooks'=>['provider-outage'=>'docs/runbooks/PROVIDER-OUTAGE.md','scanner-outage'=>'docs/runbooks/SCANNER-OUTAGE.md','deletion-pending'=>'docs/runbooks/DELETION-RECONCILIATION.md','restore'=>'docs/runbooks/RESTORE.md']];}
    public static function synthetic(): array {return ['provider'=>self::check(fn()=>ProviderRegistry::store()),'keyring'=>self::check(fn()=>Keyring::assertReady()),'audit_chain'=>Audit::verifyChain(),'schema'=>Schema::ready(),'domain_file00'=>DomainRegistry::has('file00'),'domain_file17'=>DomainRegistry::has('file17')];}
    private static function check(callable $f): bool {try{$f();return true;}catch(\Throwable){return false;}}
    public static function alert(string $severity,string $code,array $context=[]): array {$row=['actor_id'=>0,'severity'=>in_array($severity,['info','warning','critical'],true)?$severity:'warning','code'=>Utils::key($code,96),'context'=>Utils::redact($context),'status'=>'open','created_at'=>Utils::now()];$row=RecordStore::put('alert',Utils::id('alt'),$row);if(function_exists('do_action'))do_action('scm_operator_alert',$row);return $row;}
}

final class WebhookService {
    public static function verify(string $provider,string $eventId,int $timestamp,string $body,string $signature,string $secret,int $maxSkew=300): array {if(abs(Utils::now()-$timestamp)>$maxSkew)throw new Error('webhook_timestamp_invalid','Webhook timestamp outside allowed skew.',403);if(strlen($secret)<32)throw new Error('webhook_secret_invalid','Webhook secret invalid.',503);$expected=Utils::b64url(hash_hmac('sha256',$provider.'|'.$eventId.'|'.$timestamp.'|'.hash('sha256',$body),$secret,true));if(!hash_equals($expected,$signature))throw new Error('webhook_signature_invalid','Webhook signature invalid.',403);$id=hash('sha256',$provider.'|'.$eventId);$existing=RecordStore::get('webhook',$id);if($existing)return ['replay'=>true,'record'=>$existing];$record=RecordStore::put('webhook',$id,['actor_id'=>0,'provider'=>Utils::key($provider,64),'event_id'=>Utils::text($eventId,191),'body_hash'=>hash('sha256',$body),'status'=>'accepted','created_at'=>Utils::now()]);return ['replay'=>false,'record'=>$record];}
}
