<?php
declare(strict_types=1);
namespace Sabri\CentralMedia;
final class DeliveryService {
    private static array $revoked=[];
    public static function issue(array $asset,array $audience,int $ttl=300): string { Utils::requireRuntime(); $assetId=(string)($asset['asset_id']??''); $current=RecordStore::get('asset',$assetId); if($current) $asset=$current; foreach(['asset_id','owner_domain','owner_object','object_version','object_key','privacy_class'] as $f) if(empty($asset[$f])) throw new Error('asset_delivery_incomplete','Asset delivery record incomplete.',503,['field'=>$f]); if(($asset['status']??'')!=='ready'||($asset['scan_status']??'')!=='passed') throw new Error('asset_not_deliverable','Asset has not passed quarantine and required scans.',409); Auth::domainDecision((string)$asset['owner_domain'],'authorize_delivery',['asset'=>$asset,'audience'=>$audience]); $gid=Utils::id('gr'); return Crypto::sign(['grant_id'=>$gid,'asset_id'=>$asset['asset_id'],'object_key'=>$asset['object_key'],'owner_domain'=>$asset['owner_domain'],'owner_object'=>$asset['owner_object'],'object_version'=>(int)$asset['object_version'],'privacy_class'=>$asset['privacy_class'],'audience_hash'=>Utils::hashReference(Utils::json($audience))],$ttl); }
    public static function consume(string $token,array $audience): string { Utils::requireRuntime(); $c=Crypto::verify($token); $asset=RecordStore::get('asset',(string)$c['asset_id']); if($asset && (($asset['status']??'')!=='ready'||($asset['scan_status']??'')!=='passed'||(int)$asset['object_version']!==(int)$c['object_version']||!hash_equals((string)$asset['object_key'],(string)$c['object_key']))) throw new Error('grant_asset_state_changed','Asset state changed after grant issuance.',403); if(isset(self::$revoked[$c['grant_id']])) throw new Error('grant_revoked','Delivery grant revoked.',403); if(!hash_equals((string)$c['audience_hash'],Utils::hashReference(Utils::json($audience)))) throw new Error('grant_audience_mismatch','Delivery audience mismatch.',403); Auth::domainDecision((string)$c['owner_domain'],'authorize_delivery',$c+['audience'=>$audience]); return ProviderRegistry::store()->get((string)$c['object_key']); }
    public static function revoke(string $grantId): void { self::$revoked[$grantId]=true; Audit::record('delivery_grant_revoked',['grant_id'=>$grantId]); }
}
