<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php';
use Sabri\CentralMedia\{Policy,TransferService,WorkspaceUploadService,Crypto,LocalObjectStore,ProviderRegistry,DomainRegistry,DeliveryService,UploadService,IntegrationRegistry,Error};
$p=policy(); ok($p['max_upload_parts']===10000,'policy bounds'); $bad=$p;$bad['required_scans']=[];err(fn()=>Policy::validate($bad,true),'policy_malware_scan_required','malware scan fail closed');
$t=TransferService::validateEnvelope(['native_transfer_id'=>'smail:1','native_transfer_version'=>1,'sender_user_id'=>11,'recipient_type'=>'user','recipient_reference'=>'12','expected_size'=>TransferService::MAX_FILE_BYTES,'media_class'=>'document','declared_name'=>'../Clinical Notes.pdf']);ok($t['declared_name']==='Clinical-Notes.pdf'&&strlen($t['recipient_ref_hash'])===64,'transfer normalization');err(fn()=>TransferService::validateEnvelope(['native_transfer_id'=>'x','native_transfer_version'=>1,'sender_user_id'=>11,'recipient_type'=>'user','recipient_reference'=>'12','expected_size'=>TransferService::MAX_FILE_BYTES+1,'media_class'=>'document','declared_name'=>'x.pdf']),'transfer_file_size_exceeded','hard 1 GiB ceiling');
$i=WorkspaceUploadService::normalizeContext('image',['source'=>'camera','rotation_degrees'=>90,'compression_quality'=>75,'crop_requested'=>true,'crop_x'=>0,'crop_y'=>0,'crop_width'=>10,'crop_height'=>20]);ok($i['strip_location_metadata']===true&&$i['crop']['width']===10,'image workspace privacy');err(fn()=>WorkspaceUploadService::normalizeContext('image',['rotation_degrees'=>45]),'image_rotation_invalid','invalid rotation');
$c=Crypto::verify(Crypto::sign(['asset_id'=>'a'],60));ok($c['asset_id']==='a','signed grant');
$store=new LocalObjectStore();ProviderRegistry::register('local-private',$store);$put=$store->put(str_repeat('a',64),'secret',['token'=>'redact']);ok($store->get(str_repeat('a',64))==='secret'&&$put['size']===6,'encrypted object roundtrip');
DomainRegistry::register('file17','1.0.0',['authorize_delivery'=>fn($x)=>['authorized'=>true,'allowed'=>true,'object_version'=>1],'authorize_download'=>fn($x)=>['authorized'=>true,'allowed'=>true,'object_version'=>1],'authorize_transfer_create'=>fn($x)=>['authorized'=>true,'allowed'=>true,'object_version'=>1],'authorize_transfer_revoke'=>fn($x)=>['authorized'=>true,'allowed'=>true,'object_version'=>1],'authorize_deletion'=>fn($x)=>['authorized'=>true,'allowed'=>true,'object_version'=>1],'retention_decision'=>fn($x)=>['retain_until'=>time()+3600]]);
$asset=['asset_id'=>'a1','owner_domain'=>'file17','owner_object'=>'m1','object_version'=>1,'object_key'=>str_repeat('a',64),'privacy_class'=>'C3','status'=>'ready','scan_status'=>'passed'];$token=DeliveryService::issue($asset,['user_id'=>12],60);ok(DeliveryService::consume($token,['user_id'=>12])==='secret','domain reauthorized delivery');err(fn()=>DeliveryService::consume($token,['user_id'=>13]),'grant_audience_mismatch','audience binding');
$m=IntegrationRegistry::manifest();ok($m['canonical_owner']==='binary-processing-storage-delivery'&&$m['identity_owner']==='file00','ownership manifest');
echo "ALL UNIT TESTS PASSED\n";
